### DISCUSSION TITLE
👁🍬 Smooth caret in Atom

### DISCUSSION THREAD

**Discussion by unrealapex** [atom/atom#22300] [Ideas]
It would be nice to have an option for smooth caret in Atom similar to what is implemented in Visual Studio Code and other Microsoft products. I know that several Atom users have done this by hacking Atom by adding this css snippet to their stylesheet
```css
atom-text-editor .cursor {
  transition: all 80ms;
}

atom-text-editor .selection {
  border-radius: 4px;
  transition: all 20ms;
}
``` 

but it would be easier if this feature was built in and would just need to be toggled.

![demo](https://user-images.githubusercontent.com/10027925/108513034-f9034c00-72fc-11eb-8674-d5d2ca33ca94.gif)
![demo2](https://user-images.githubusercontent.com/10027925/108512188-d0c71d80-72fb-11eb-84ea-48e722384bd1.gif)
![demo3](https://user-images.githubusercontent.com/10027925/108512246-e76d7480-72fb-11eb-9733-5824d6cd8db4.gif)

### Sources
These images were copied from issue [#9221](https://github.com/microsoft/terminal/issues/9221) in the [Windows Terminal repo](https://github.com/microsoft/terminal/) 

The smooth caret snippet is from [this website](https://ninoan.com/smooth-cursor-motion/) referenced in the original issue [#20310](https://github.com/microsoft/vscode/issues/20310) in the [Visual Studio Code repo](https://github.com/microsoft/vscode/).
