### DISCUSSION TITLE
PHP Syntax highlighting bug ?

### DISCUSSION THREAD

**Discussion by Tomdazy** [atom/atom#22321] [Q&A] [answered]
Hi everyone, I just started Atom today to find that in my PHP files the `$` characters at the beginning of variables are not colorized...
Can anyone help me to fix that ? (I didn't find anywhere in the settings to fix it and checking the git of my atom config I don't see any changes 😅)

![image](https://user-images.githubusercontent.com/29003255/116668001-26274700-a99d-11eb-8170-4dfd6ed0bf10.png)

**Comment by UziTech** [comment, marked as answer]
You could change the colors by changing your syntax theme or adding something to your Atom stylesheet

```css
.syntax--php.syntax--variable.syntax--punctuation {
	color: whatever color you want
}
```
