### DISCUSSION TITLE
Some of the css color formatting is gone, what do I do?

### DISCUSSION THREAD

**Discussion by OrochiAM** [atom/atom#22410] [Q&A]
![image](https://user-images.githubusercontent.com/32849778/118025639-5d640380-b360-11eb-8538-2952e689b6e2.png)
![image](https://user-images.githubusercontent.com/32849778/118025719-7076d380-b360-11eb-9672-ff72f02fa81c.png)
It's minimal, it's just special characters like # or @ but it's really bugging me.
It's also this way in safe mode.

**Comment by chbk** [comment]
It's because the One Dark theme colors punctuation the same way across languages now. However an exception was planned for CSS to keep those original colors. It requires https://github.com/atom/language-css/pull/167 to be merged and language-css to switch to Tree-sitter by default.

In the meantime, you can open `~/.atom/styles.less` and add:
```css

.syntax--css .syntax--keyword .syntax--punctuation,
.syntax--css .syntax--constant .syntax--punctuation {
  color: inherit;
}

```

**Reply by ThatXliner** [reply]
I see code duplication...
```less
.syntax--css {
  .syntax--keyword,.syntax--constant {
   .syntax--punctuation {
      color: inherit;
    }
  }
}
```
Oh wait, that's not as short.
