### DISCUSSION TITLE
Change C language syntax color

### DISCUSSION THREAD

**Discussion by shd8698766** [atom/atom#22539] [Q&A]
Hi, for example macros display in multiple colors, how can I change macros to one color?

**Comment by icecream17** [comment]
If I remember correctly you can (edit the `styles.less` file) and (use the classes from inspect element) and (the css color property) to change the text color of anything. I'm pretty sure there's a similar answer about this somewhere

https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks

Examples

```css
.syntax--potato.syntax--strawberry.syntax--ice {
  color: rebeccapurple;
}

.syntax--comment {
  font-size: 10em;
}
```
