### DISCUSSION TITLE
Zero padding number lines

### DISCUSSION THREAD

**Discussion by Bilbo-Sparkle** [atom/atom#22747] [Q&A]
Hi everybody,
after _A_LOT_ of effort I managed to recover the information lost in this post:
https://discuss.atom.io/t/can-i-pad-the-line-numbers-with-zeros-in-front/18861

In it the say you have to put this in styles.less:

atom-text-editor::shadow {
  .line-number {
    &-0::before,
    &-1::before,
    &-2::before,
    &-3::before,
    &-4::before,
    &-5::before,
    &-6::before,
    &-7::before,
    &-8::before {
      content: '0';
      position: absolute;
    }
  }
}

After trying it the program complains about the use of deprecated syntax. Well, I searched the documentation and changed it in this way:

atom-text-editor {
  .syntax--line-number {
    &-0::before,
    &-1::before,
    &-2::before,
    &-3::before,
    &-4::before,
    &-5::before,
    &-6::before,
    &-7::before,
    &-8::before {
      content: '0';
      position: absolute;
    }
  }
}

But this didn't work either.
Could somebody help me? (thanks)

**Comment by icecream17** [comment]
Future: `ctrl+shift+i` Select element. (Google select element devtools). Then look at element class

![image](https://user-images.githubusercontent.com/58114641/126094289-4495b831-7384-457c-b6c0-f1824ac541e6.png)

```css
.line-number::before {content: '0';}
```

**Reply by Bilbo-Sparkle** [reply]
Thank you very much!
That almost worked. But puts zeros in every single line.
The original intended purpose of the lost link was to fill with zeros till 3 or 4 characters. Past that point write line numbers normally.
I've been using Atom just for a couple of days and I have not the level to fix this for myself.
Could somebody write a couple more lines or so to get the intended behaviour?

Moreover, great tip that of "Ctrl-Shift-I"; very handy. :)

P.S.: I usually take a long time to answer because I suffer of a severe disease.

**Reply by icecream17** [reply]
How did you recover the website information?

Anyways here's a bruteforce solution. I used `data-buffer-row` but `data-screen-row` seems the same.

Also `data-buffer-row=0` visually changes line number 1

At the bottom you can see the code I used to make this
```css
.line-number[data-buffer-row="0"]::before {content: '0';}
.line-number[data-buffer-row="1"]::before {content: '0';}
.line-number[data-buffer-row="2"]::before {content: '0';}
.line-number[data-buffer-row="3"]::before {content: '0';}
.line-number[data-buffer-row="4"]::before {content: '0';}
.line-number[data-buffer-row="5"]::before {content: '0';}
.line-number[data-buffer-row="6"]::before {content: '0';}
.line-number[data-buffer-row="7"]::before {content: '0';}
.line-number[data-buffer-row="8"]::before {content: '0';}
.line-number[data-buffer-row="9"]::before {content: '0';}
.line-number[data-buffer-row="10"]::before {content: '0';}
.line-number[data-buffer-row="11"]::before {content: '0';}
.line-number[data-buffer-row="12"]::before {content: '0';}
.line-number[data-buffer-row="13"]::before {content: '0';}
.line-number[data-buffer-row="14"]::before {content: '0';}
.line-number[data-buffer-row="15"]::before {content: '0';}
.line-number[data-buffer-row="16"]::before {content: '0';}
.line-number[data-buffer-row="17"]::before {content: '0';}
.line-number[data-buffer-row="18"]::before {content: '0';}
.line-number[data-buffer-row="19"]::before {content: '0';}
.line-number[data-buffer-row="20"]::before {content: '0';}
.line-number[data-buffer-row="21"]::before {content: '0';}
.line-number[data-buffer-row="22"]::before {content: '0';}
.line-number[data-buffer-row="23"]::before {content: '0';}
.line-number[data-buffer-row="24"]::before {content: '0';}
.line-number[data-buffer-row="25"]::before {content: '0';}
.line-number[data-buffer-row="26"]::before {content: '0';}
.line-number[data-buffer-row="27"]::before {content: '0';}
.line-number[data-buffer-row="28"]::before {content: '0';}
.line-number[data-buffer-row="29"]::before {content: '0';}
.line-number[data-buffer-row="30"]::before {content: '0';}
.line-number[data-buffer-row="31"]::before {content: '0';}
.line-number[data-buffer-row="32"]::before {content: '0';}
.line-number[data-buffer-row="33"]::before {content: '0';}
.line-number[data-buffer-row="34"]::before {content: '0';}
.line-number[data-buffer-row="35"]::before {content: '0';}
.line-number[data-buffer-row="36"]::before {content: '0';}
.line-number[data-buffer-row="37"]::before {content: '0';}
.line-number[data-buffer-row="38"]::before {content: '0';}
.line-number[data-buffer-row="39"]::before {content: '0';}
.line-number[data-buffer-row="40"]::before {content: '0';}
.line-number[data-buffer-row="41"]::before {content: '0';}
.line-number[data-buffer-row="42"]::before {content: '0';}
.line-number[data-buffer-row="43"]::before {content: '0';}
.line-number[data-buffer-row="44"]::before {content: '0';}
.line-number[data-buffer-row="45"]::before {content: '0';}
.line-number[data-buffer-row="46"]::before {content: '0';}
.line-number[data-buffer-row="47"]::before {content: '0';}
.line-number[data-buffer-row="48"]::before {content: '0';}
.line-number[data-buffer-row="49"]::before {content: '0';}
.line-number[data-buffer-row="50"]::before {content: '0';}
.line-number[data-buffer-row="51"]::before {content: '0';}
.line-number[data-buffer-row="52"]::before {content: '0';}
.line-number[data-buffer-row="53"]::before {content: '0';}
.line-number[data-buffer-row="54"]::before {content: '0';}
.line-number[data-buffer-row="55"]::before {content: '0';}
.line-number[data-buffer-row="56"]::before {content: '0';}
.line-number[data-buffer-row="57"]::before {content: '0';}
.line-number[data-buffer-row="58"]::before {content: '0';}
.line-number[data-buffer-row="59"]::before {content: '0';}
.line-number[data-buffer-row="60"]::before {content: '0';}
.line-number[data-buffer-row="61"]::before {content: '0';}
.line-number[data-buffer-row="62"]::before {content: '0';}
.line-number[data-buffer-row="63"]::before {content: '0';}
.line-number[data-buffer-row="64"]::before {content: '0';}
.line-number[data-buffer-row="65"]::before {content: '0';}
.line-number[data-buffer-row="66"]::before {content: '0';}
.line-number[data-buffer-row="67"]::before {content: '0';}
.line-number[data-buffer-row="68"]::before {content: '0';}
.line-number[data-buffer-row="69"]::before {content: '0';}
.line-number[data-buffer-row="70"]::before {content: '0';}
.line-number[data-buffer-row="71"]::before {content: '0';}
.line-number[data-buffer-row="72"]::before {content: '0';}
.line-number[data-buffer-row="73"]::before {content: '0';}
.line-number[data-buffer-row="74"]::before {content: '0';}
.line-number[data-buffer-row="75"]::before {content: '0';}
.line-number[data-buffer-row="76"]::before {content: '0';}
.line-number[data-buffer-row="77"]::before {content: '0';}
.line-number[data-buffer-row="78"]::before {content: '0';}
.line-number[data-buffer-row="79"]::before {content: '0';}
.line-number[data-buffer-row="80"]::before {content: '0';}
.line-number[data-buffer-row="81"]::before {content: '0';}
.line-number[data-buffer-row="82"]::before {content: '0';}
.line-number[data-buffer-row="83"]::before {content: '0';}
.line-number[data-buffer-row="84"]::before {content: '0';}
.line-number[data-buffer-row="85"]::before {content: '0';}
.line-number[data-buffer-row="86"]::before {content: '0';}
.line-number[data-buffer-row="87"]::before {content: '0';}
.line-number[data-buffer-row="88"]::before {content: '0';}
.line-number[data-buffer-row="89"]::before {content: '0';}
.line-number[data-buffer-row="90"]::before {content: '0';}
.line-number[data-buffer-row="91"]::before {content: '0';}
.line-number[data-buffer-row="92"]::before {content: '0';}
.line-number[data-buffer-row="93"]::before {content: '0';}
.line-number[data-buffer-row="94"]::before {content: '0';}
.line-number[data-buffer-row="95"]::before {content: '0';}
.line-number[data-buffer-row="96"]::before {content: '0';}
.line-number[data-buffer-row="97"]::before {content: '0';}
.line-number[data-buffer-row="98"]::before {content: '0';}
```

```js
string = ''
for (let i = 0; i < 99; i++) { // Two digits
    string += `.line-number[data-buffer-row="${i}"]::before {content: '0';}\n`
}
```
