### ISSUE TITLE
Corrupted blob-store (SyntaxError: Unexpected end of input)

### ISSUE THREAD

**Issue by Razum** [atom/atom#10015]
Hi Guys.
**OS**: Ubuntu 14.04
**Atom version:** 1.3.0
**Reproducable in safe mode**

After upgrading Atom to 1.3.0 version it has started crashing and throwing the following error on start from command line:

![Error img](http://i.imgur.com/8bcvN6N.png) 

```javascript
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at FileSystemBlobStore.load (/opt/atom/resources/app.asar/src/file-system-blob-store.js:31:31)
    at Function.load (/opt/atom/resources/app.asar/src/file-system-blob-store.js:10:14)
    at window.onload (file:///opt/atom/resources/app.asar/static/index.js:18:39)

handleSetupError @ index.js:61
```

**Config:**

```
"*":
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
  jshint:
    supportLintingJsx: true
    harmony: true
    esnext: true
  "atom-beautify":
    _analyticsUserId: "bc2b80b6-ea35-44a1-a6d5-4d7c7f1f78a3"
    js_end_with_newline: true
    js_keep_array_indentation: true
    js_keep_function_indentation: true
    js_space_after_anon_function: true
  "one-light-ui": {}
  jsformat: {}

```
**Installed packages:**
```
/home/roman/.atom/packages (10)
├── atom-beautify@0.28.19
├── autocomplete-paths@1.0.2
├── color-picker@2.0.14
├── file-icons@1.6.13
├── highlight-selected@0.11.1
├── jshint@1.8.3
├── linter@1.11.3
├── linter-csslint@1.1.0
├── pigments@0.19.2
└── react@0.12.10

```
