### ISSUE TITLE
Can't change whitespace characters color!

### ISSUE THREAD

**Issue by bobsilon** [atom/atom#10392]
Hi there,
I want to change the color of whitespace characters. I wrote below style in Atom stylesheet file:
```css
atom-text-editor .invisible-character,
atom-text-editor .leading-whitespace,
:host .invisible-character {
  color: #f55!important;
}
```
But the color stays same as default. Did I wrote wrong selector?

**Comment by MaximSokolov** [comment]
This should work:
```less
atom-text-editor::shadow {
  .leading-whitespace, .invisible-character {
    color: #f55;
  }
}
```
