### ISSUE TITLE
Line-Height rendering problem when using Hack (the font)

### ISSUE THREAD

**Issue by kylekthompson** [atom/atom#10417]
I am running into an issue where a few lines (multiple places in multiple files) are too close to each other when I am using the Hack font (everything looks fine with the default font, but I haven't tried other fonts).

Note: this is a fresh install of Atom (deleted from Applications, deleted .atom folder, reinstalled).

Here is a picture of the issue:
![Picture 1](https://cloud.githubusercontent.com/assets/6563105/12329325/d4435958-baad-11e5-9e5b-d98c7c4b63b3.png)

Here is the same spot after disabling the line-height modifier in the CSS (with the developer tools):
![Picture 2](https://cloud.githubusercontent.com/assets/6563105/12329346/f50efb74-baad-11e5-947c-12f2c2958aac.png)

The CSS for Picture 1:

```CSS
atom-text-editor {
    font-size: 14px;
    font-family: Hack;
    line-height: 1.5;
}
```

The CSS for Picture 2:

```CSS
atom-text-editor {
    font-size: 14px;
    font-family: Hack;
}
```

Any suggestions?
