### ISSUE TITLE
Font "SourceHanCode JP" is not working.

### ISSUE THREAD

**Issue by higeaaa** [atom/atom#11169]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

I have "[Source Han Code Pro](https://github.com/adobe-fonts/source-han-code-jp)" installed myPC(windows7) cause I want to use the default font on atom. 
Setting font-family on `styles.less` is not working.

```styles.less
 atom-text-editor {
   font-family: "Source Han Code JP Light", "SourceHanCodeJP-Light";
 }
```

### Versions

```
$ atom --version
1.5.3

$ apm -v
apm  1.6.0
npm  2.13.3
node 0.10.40
python
git
visual studio
```

**Comment by 50Wliu** [comment]
Can you please try `atom-text-editor::shadow`?

**Comment by higeaaa** [comment]
@50Wliu Thank you for your advise. I try `atom-text-editor::shadow`, but it is not worked.

```less
atom-text-editor {
   font-family: "Source Han Code JP Light", "SourceHanCodeJP-Light";
}
atom-text-editor::shadow  * {
  font-family: "Source Han Code JP Light", "SourceHanCodeJP-Light";
}
```

**Comment by damieng** [comment]
Font-family can not accept weights - that is a limitation of CSS. You can however do this:

1. Set Source Han Code JP as the font in File > Settings
2. Open Config Folder and edit styles.less
3. Set atom-text-editor to:

```less
atom-text-editor {
  font-weight: 300;
}
```

This will correctly choose the Light weight which is only marked as 'L' in this font so you need to use the numeric equivalent instead.

![sourcehancode](https://cloud.githubusercontent.com/assets/118951/13801119/288ec074-eaec-11e5-8fbb-a9eaabeb3260.PNG)
