### ISSUE TITLE
I want to change color element of sidebar only 1 color?

### ISSUE THREAD

**Issue by tnthao10** [atom/atom#11291]
Hi guys,
I want to change color element of sidebar only 1 color? How?
http://i.imgur.com/dr9cbJ9.png
Color of Name file and Name folder not uniform, i want it is only color black like folder 'css', 'languages' in this image.
Plese help me....

**Comment by mnquintana** [comment]
Hey there! You'll have better luck asking for help on [Discuss](https://discuss.atom.io/) (Atom's forum) or [Slack](http://atom-slack.herokuapp.com/) – GitHub Issues are for reporting bugs or enhancement requests.

:beers:

**Comment by mnquintana** [comment]
The coloring in the tree view is a result of Atom's git integration – the orange in your screenshot indicates that those files / directories have been modified, and green indicates that they are new since the last commit.

Unfortunately it's not possible to disable outright right now (though you can subscribe to https://github.com/atom/tree-view/issues/657 for updates on that!), but in the meantime you can modify your Custom Styles file (`styles.less`) to disable the coloring:

*(From https://github.com/atom/tree-view/issues/657#issuecomment-172699560)*
```less
// remove Git colors from tree-view
.tree-view {
  .status-modified,
  .status-added,
  .status-renamed,
  .status-removed {
    color: inherit !important; // remove diff color

    &.directory > .list-item {
      color: inherit !important; // remove diff color
    }
    &.directory.selected > .list-item {
      color: @text-color-selected !important; // add selected color
    }
  }
}
```

Hope that helps!
