### ISSUE TITLE
Decompose ligatures when the cursor is in/beside them

### ISSUE THREAD

**Issue by JoeyEremondi** [atom/atom#11567]
### Description

I use FiraCode2 with ligature support in Atom, and for the most part it's very nice.

However, I find it very difficult to edit ligatures. For example, I often need to change <$> to <*> in Haskell, but Atom does not show where in the ligature the cursor is, and I often lose time erasing the wrong part of the ligature.
Similarly, I will often try to delete the space before an arrow -> , but I end up deleting the first dash - because the cursor is shown beside the ligature, even when its actual position is in the middle.

Ideally, when the cursor was at the edge of, or inside a ligature, it would be rendered not as the single character, but as the actual simple characters which make it up.

Is this possible? If it is not, consider this a request that it be added, or at least supported in a package.

Thanks!

### Steps to Reproduce

1. Set the font to FiraCode, HaskLig, or another ligature-supporting font
2. Enter a ligature, such as `->`
3. Move the cursor from one side to the ligature of the other

**Expected behavior:** The ligature is decomposed into its constituent characters, or the cursor is shown inside the ligature.

**Actual behavior:** The cursor remains to the right of the ligature.

### Versions

I've tested in 1.7.1, but it showed up in all previous versions I'd used.

**Comment by bj7** [comment]
What OS are you on?

**Comment by JoeyEremondi** [comment]
@bj7 I'm on Linux. 

I just tried it with Atom 1.7.2 on Windows, and the cursors show up in the middle of the ligature, which solves the problem. 

I'd initially thought this was a feature request, but maybe this is a bug on Linux?

If it helps, the linux stylesheet is as follows:

```css
// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
  text-rendering: optimizeLegibility;
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```
