### ISSUE TITLE
Styling tabs icons

### ISSUE THREAD

**Issue by Thegreen0ne** [atom/atom#12304]
![atom](https://cloud.githubusercontent.com/assets/5232291/17366343/b93810c8-5958-11e6-8b80-c73cd2d61298.png)

For some reason I haven't been able to style the icons in the editor's tabs... Cannot use .tab .title::before in my stylesheet to up the font size. Can somebody help me on that?

**Comment by simurai** [comment]
@Thegreen0ne Are you using the `file-icons` package? It probably needs a stronger selector or `!important`  should also work, like:

```less
.tab .title::before {
  font-size: 24px !important;
}
```
