### ISSUE TITLE
Feature Request: Separate themes in config.cson

### ISSUE THREAD

**Issue by DamnedScholar** [atom/atom#12484]
Right now, the themes in `config.cson` are defined under one key.

```
"*":
  core:
    themes: [
      "one-dark-ui"
      "firewatch-green-syntax"
    ]
```

[Over on the forum](https://discuss.atom.io/t/per-project-themes/16064), a few people have requested to be able to change the theme according to their project. Some people design themes for specific languages or tasks. It seems like it would be a trivial change to split these to be under two keys, and that would allow packages or `init.cson` to more easily manipulate the themes without having to mess with an array and identify which theme is which based on the last word of the name.

```
"*":
  core:
    theme-ui: "one-dark-ui"
    theme-syntax: "firewatch-green-syntax"
```
