### ISSUE TITLE
LESS styles not taking effect in styles.less

### ISSUE THREAD

**Issue by TeejayParker** [atom/atom#14532]
I have been trying to edit my styles.less, but when I do, the changes do not take effect.

Example:

`atom-text-editor.editor .cursor {
  color: green;
}`

Shouldn't that change the cursor to green?  Or am I just not understanding this properly?

any help would be great!  Thanks!

**Comment by TeejayParker** [comment]
To be more clear of what I'm trying to accomplish, I'm trying to change the modified treeview colors.  

Was following this:  http://blog.atom.io/2014/03/13/git-integration.html

But that appears to not be working.

**Comment by arcticicestudio** [comment]
Maybe try to get help in the [discuss forum](https://discuss.atom.io) which can be used by users to get help about the usage, the repository issues should be used for develoment purposes only.
The color for the git status are constrolled by the syntax theme variables
```css
@syntax-color-added
@syntax-color-modified
@syntax-color-removed
@syntax-color-renamed
```
Paste this into your `styles.less` file and insert the colors you'd like to use:
```css
.tree-view {
  .list-tree li:not(.list-nested-item) {
    &.status-added {
      color: /*<YOUR COLOR>*/;
    }
    &.status-modified {
      color: /*<YOUR COLOR>*/;
    }
    &.status-removed {
      color: /*<YOUR COLOR>*/;
    }
    &.status-renamed {
      color: /*<YOUR COLOR>*/;
    }
  }
}
```
