### ISSUE TITLE
How to disable tips on Atom editor

### ISSUE THREAD

**Issue by guitexa** [atom/atom#16320]
I'd like to know how to disable that tips when I choose between options on that pop-up, the image explain my doubt. Thanks

https://i.stack.imgur.com/RCCB7.jpg

**Comment by victorhqc** [comment]
You could toggle the `developer tools` in `View` -> `Developer` -> `Toggle Developer Tools`, Inspect the element (like a regular website) get the css `classname`, then go to `Atom` -> `Stylesheet..` and add a new css rule.
```css
.the-css-class-you-find {
  display: none;
}
```

Just make sure you get all the parent classes too or you might end up hiding more than you intend.

**Comment by 50Wliu** [comment]
Great timing @victorhqc :).  There is no way to disable it but you can follow @victorhqc's instructions to hide the description.

**Comment by guitexa** [comment]
Hi @victorhqc, I appreciate your help, but it's very complicate.
I found something on C:\Users\%USER%\.atom\packages\atom-material-ui\styles\overlays.less
But I couldn't remove that message.
If someone could help I'd appreciate, because that messages is very boring.
Thanks

**Comment by sawim** [comment]
Looks like the node you want has `.suggestion-description` for it's class.
It has `display` as an inline style, so I think you'll have to nuke the specificity with !important .

```css
/* styles.less */
atom-text-editor .suggestion-description {
  display: none !important;
}
```
