### ISSUE TITLE
Reflow jumbles separate lines together

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18020]
_From @joallard on October 18, 2016 12:39_

This is following burodepeper/language-markdown#144. I searched briefly if the issue was already existing, sorry if it's a dupe.

---

To be clear, this happens when the heading and paragraph are not separated by an empty line.

``` gherkin
Given I have markdown
  """
  ## Oh how headers are useful
  This is a paragraph with some text that will make it go over the line of 80 characters. It is a paragraph, and we want it to be separate from the heading.
  """
And I put the caret between "This" and "is"
When I invoke Reflow (Alt-Cmd-Q)
Then only the paragraph should be reflown
```

Actual:

``` md
## Oh how headers are useful This is a paragraph with some text that will make
## it go over the line of 80 characters. It is a paragraph, and we want it to be
## separate from the heading.
```

_Copied from original issue: atom/autoflow#53_

**Comment by daviwil** [comment]
_From @aleb on October 10, 2017 9:22_

Another example:
```
**asdf sdfa** sdf asdf asd fsad fasd fsdf asdf asdf asdf asd fasdf a asdf dsfa af ads adsf 
```
After cmd+alt+q:
```
**asdf sdfa** sdf asdf asd fsad fasd fsdf asdf asdf asdf asd fasdf a asdf dsfa
**af ads adsf 
```

**Comment by daviwil** [comment]
_From @joallard on October 28, 2017 0:16_

This is also the case for YAML:

Before:
```yaml
key:
  other_key:
    This is a paragraph with some text that will make it go over the line of 80 characters. It is a paragraph, and we want it to be separate from the heading.  # <= cursor here, cmd-alt-q
```

After:
```yaml
key: other_key: This is a paragraph with some text that will make it go over the
line of 80 characters. It is a paragraph, and we want it to be separate from the
heading.
```
