### ISSUE TITLE
Style atom windows individually

### ISSUE THREAD

**Issue by Davidslv** [atom/atom#18138]
## Summary

Very often I need to work on multiple projects at the same time, so sometimes I have 3+ atom windows open and I can't visually distinguish which project the window relates.

## Motivation

The motivation is to be able to distinguish between projects through colour coding or using a different theme. Currently if I change the theme in one window I'm changing it on all atom windows.
If I could have a way to lock a theme to a specific window that would help me identify on what project I'm working on.

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

- I've considered changing the Themes, but it changes globally (all windows)
- I've tried to find a way to customize it but I'm not sure there's currently a way?

## Additional context

If you know of a current way please let me know.

Thank you!

**Comment by simurai** [comment]
A hack you could try is adding a colored stripe next to project names. Paste the following in your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// Color code your projects
.project-root-header {
  .name[data-name]:after {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    width: 4px;
  }

  // Add project names and colors below
  .name[data-name="atom"]:after { background-color: red; }
  .name[data-name="github"]:after { background-color: blue; }
}
```

And adjust the project names and colors.

![screen shot 2018-10-02 at 2 57 08 pm](https://user-images.githubusercontent.com/378023/46331643-e0266d00-c653-11e8-9e32-98630fc7abe5.png)

Also, works when adding multiple projects per window.
