### ISSUE TITLE
[git-diff] option to show markers on the right side of line numbers (instead of left side)

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18670]
## Summary

It'd be nice to have an option to show markers on the right side of line numbers (instead of the left side).

## Motivation

When the file explorer pane is open, it is easy to see the markers. For example:

![screen shot 2019-01-09 at 5 18 27 pm](https://user-images.githubusercontent.com/297678/50939636-9a3b2b00-1432-11e9-95e2-84171d20e9ae.png)

But when the file explorer is closed, and a window in the background has white color, it makes the markers difficult to see. For example:

![screen shot 2019-01-09 at 5 19 47 pm](https://user-images.githubusercontent.com/297678/50939700-cbb3f680-1432-11e9-9ad9-eeec0717d198.png)

## Describe alternatives you've considered

For now, I can select the `Show Icons In Editor Gutter` option, which works, but isn't as visually appealing and takes up more horizontal space. For example:

![screen shot 2019-01-09 at 5 21 23 pm](https://user-images.githubusercontent.com/297678/50939761-0322a300-1433-11e9-97d6-cf788e909ba5.png)

Not only do the icons take more space, but you can see they're also mis-aligned.

**Comment by rsese** [comment]
Thanks for the feedback!

> But when the file explorer is closed, and a window in the background has white color, it makes the markers difficult to see. 

It sounds like the motivation is improving the visibility of the markers and so related to discussions like https://github.com/atom/git-diff/pull/79 for example.  That pull request wasn't merged because there are styles you can add to your styles file to help make the markers more prominent (the suggested CSS would need to be tweaked but still works I think).

I think you can also switch the side with CSS as well:

```css
atom-text-editor .gutter .line-number.git-line-added {
  border-left: none;
  border-right: 2px solid @syntax-color-added;
}
```

![right-marker](https://github-slack.s3.amazonaws.com/monosnap/styles.less__.atom_2019-01-10_12-35-47.png)

So since there are style changes that can be made to your styles file that can help, we'll close this out since we prefer that folks take advantage of Atom's customizability where possible.

**Comment by trusktr** [comment]
That indeed is an easy fix for the lines-based style. However for the icon-based style, wouldn't it be better to follow conventions and add a custom gutter for the dots? This may be cleaner, and also result in aligned dots like

<img width="194" alt="screen shot 2019-01-11 at 1 56 49 pm" src="https://user-images.githubusercontent.com/297678/51061639-d1cbe380-15a8-11e9-89cd-cdd4369548e1.png">

instead of

<img width="202" alt="screen shot 2019-01-11 at 1 57 16 pm" src="https://user-images.githubusercontent.com/297678/51061647-d5f80100-15a8-11e9-981d-6f06c08b5ff2.png">

**Comment by 50Wliu** [comment]
Can you open a new issue for that, @trusktr?

**Comment by trusktr** [comment]
Sure, made a new one: https://github.com/atom/atom/issues/18684

**Comment by trusktr** [comment]
Alright, I ended with:

```less
atom-text-editor .gutter .line-number.git-line-added {
	background-color: fade( #C3E88D, 30% );
}
atom-text-editor .gutter .line-number.git-line-modified {
	background-color: fade( lighten(@syntax-color-modified, 25%), 30% );
}
atom-text-editor .gutter .line-number.git-line-removed {
	border-bottom: 1px solid lighten(@syntax-color-removed, 25%);
}
```

<img width="180" alt="screen shot 2019-01-11 at 3 04 18 pm" src="https://user-images.githubusercontent.com/297678/51063973-2fb0f900-15b2-11e9-9a05-e0adb8494756.png">
