### ISSUE TITLE
Text Rendering on macOS changed with Electron 3.0

### ISSUE THREAD

**Issue by as-cii** [atom/atom#19356]
As reported in https://github.com/atom/atom/pull/18916#issuecomment-493200137, we observed a significant change in how text is rendered on a High-DPI display on macOS after upgrading Atom to use Electron >= 3.0.

Below you can find a zoomed-in screenshot of rendering the word `Lorem` in a variety of environments. Please, click on all of the images and quickly browse through the tabs to appreciate how stark the difference is for this pull request.

### Atom on Electron 3
<img width="1501" alt="Atom on Electron 3 0" src="https://user-images.githubusercontent.com/482957/57880973-73499700-7820-11e9-915d-7acf4bde77bf.png">

### VS Code on Electron 3 (latest published version)
<img width="1501" alt="VS Code" src="https://user-images.githubusercontent.com/482957/57880976-73499700-7820-11e9-9942-edba83dd3bb5.png">

### Atom on Electron 2 (Atom 1.38.0-beta0)
<img width="1501" alt="Atom on Electron 2 0" src="https://user-images.githubusercontent.com/482957/57880977-73e22d80-7820-11e9-81c8-5c35b02e3678.png">

### Lorem on TextEdit
<img width="1501" alt="Screen Shot 2019-05-17 at 16 46 27" src="https://user-images.githubusercontent.com/482957/57936028-587c2e80-78c3-11e9-95c2-1c365b1ca359.png">

You can reproduce the above tests by using Fira Code Retina, 15px.

### Causes of the change
We believe the change was caused by upgrading to a newer Chromium version, but it is unclear whether the new rendering is wrong or not. Specifically, this seems to be related to the global "Use font smoothing when available" setting on macOS, and Atom is now just honoring that configuration. Indeed, when rendering the word `Lorem` in TextEdit (a native macOS application), we observe the same rendering as in Atom on Electron 3.

### Next steps
@rafeca and I discussed what to do about this, and it seems okay to proceed with allowing this new rendering behavior. Users can go back to the previous behavior by disabling "Use font smoothing when available", or add the following CSS to their personal style sheet:

```css
/* This will change how font-smoothing is applied to the entire Atom application */
atom-workspace {
  -webkit-font-smoothing: antialiased;
}

/* If you just want to change how text is rendered within the editor, use this instead: */
atom-text-editor {
  -webkit-font-smoothing: antialiased;
}
```

If needed, in the future we could provide a configuration parameter to change the aliasing behavior without needing to write any CSS.
