### ISSUE TITLE
Atom does not support background-clip text in css

### ISSUE THREAD

**Issue by jappeace** [atom/atom#20243]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    [x] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
   [x] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    [x] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
  [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    [x] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I wish to make an ancient vibe by having lines go trough my text in an animation.
However background-clip is not supported I think at the moment in atom.
Please upgrade electron to add support.

### Steps to Reproduce

1. Put this code into style.less:
```css
span {
    text-shadow: 0 0 .4em #30bb30;
    color: transparent;
    background-clip: text;
    background-image: repeating-linear-gradient(3deg,transparent,transparent 3%,black 3%,black 5%,transparent 5%,transparent 10%);
    background-position: 0 0;
    background-color: #30bb30;
    background-size: 100% 50px;
    animation: animatedBackground 40s linear infinite;
    -webkit-animation: animatedBackground 40s linear infinite;
}

@keyframes animatedBackground {
    from{
        background-position: 0 0;
    }
    to{
        background-position: 3px 50px;
    }
}
```
**Expected behavior:**

Something like this:

![image](https://user-images.githubusercontent.com/3874017/70868303-cd116b80-1f7f-11ea-83ff-a11d0529d535.png)

Which can be seen as an animation on the website: https://jappieklooster.nl

**Actual behavior:**

The entire background becomes like a green snake:

![image](https://user-images.githubusercontent.com/3874017/70868295-b10dca00-1f7f-11ea-8461-dbf89540faa9.png)

**Reproduces how often:**

100%

### Versions

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by Arcanemagus** [comment]
> Atom : 1.36.1

You are on an older version of Atom, but in this case that isn't going to make a difference as Chrome doesn't fully support `background-clip: text;`, even on version 81.0.3995.0. As explained in [the documentation for `background-clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip), you need to use the prefixed version of that property on Chrome (which is what Atom is based on).

Thanks for reaching out!

**Comment by jappeace** [comment]
Don't worry @Arcanemagus I figured it out:

![image](https://user-images.githubusercontent.com/3874017/71201091-9c8c4300-2299-11ea-93ad-7c04d0cd9982.png)

This is the source code I used (if anyone else encounters this problem):

```css
body:before {
    pointer-events: none;
    position: absolute;
    content: '';
    width:120%;
    height:120%;
    top: -100px;
    left: -100px;
    z-index: 10;
    background-image: repeating-linear-gradient(0deg,transparent,transparent 3%,rgba(0,255,0,0.2) 3%,rgba(0,0,0,0.5) 4%,transparent 5%,transparent 7%);
    background-position: 0 0;
    background-color: rgba(48, 187, 48, 0.1);
    background-size: 200% 100%;
    animation: animatedBackground 70s linear infinite;
}

body {
  text-shadow: 0 0 .4em #30bb30;
  border: 100px solid black;
}

@keyframes animatedBackground {
    0% {
        background-position: 0 0;
    }
    50%{
      background-position: 0px 450px;
    }
    60%{
      background-position: 0px 350px;
    }
    100% {
        background-position: 0px 900px;
    }
}

```
