### ISSUE TITLE
'editor:toggle-line-comments' breaks multi-line non-nestables block comments

### ISSUE THREAD

**Issue by ariasuni** [atom/atom#20611]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Write some code in a language where `editor:toggle-line-comments` uses block comments and where these are not nestables, e.g. CSS or HTML:
```css
body {
    font-family: sans-serif;
}
```
2. Comment the lines
```css
/*body {
    font-family: sans-serif;
}*/
```
3. Put your cursor on any line that’s not the first one, or select text except from on first line, and try to uncomment
```css
/* with cursor put on middle line */
/* body {
    /* font-family: sans-serif; */
} */

/* with cursor put on last line */
/* body {
    font-family: sans-serif;
/* } */ */

/* with the two last lines */
/* body {
    /* font-family: sans-serif;
} */ */
```

**Expected behavior:**

Trying to toggle line comments when cursor is in a block comment should uncomment the whole block.

**Actual behavior:**

It tries to comment again, producing invalid syntax for languages that don’t support nested block comments.

**Reproduces how often:**

Always

### Versions

Arch Linux

```
Atom    : 1.45.0
Electron: 4.2.12
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm  2.4.5
npm  6.14.4
node 13.12.0 x64
atom 1.45.0
python 3.8.2
git 2.26.0
```
