### ISSUE TITLE
Blurry Sidebar

### ISSUE THREAD

**Issue by whaaaley** [atom/atom#20728]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The sidebar is a bit blurry. I did some investigating though and it's related to `z-index` somehow.

```scss
.tree-view {
  // z-index: 4 !important; // blurry until sidebar small enough to trigger overflow: scroll
  // z-index: 5 !important; // sharp while resizing but blurry otherwise
  z-index: 12 !important; // sharp but can't resize the sidebar
}
```

### Steps to Reproduce

1. Resize the sidebar super wide
2. Resize the sidebar super small
3. Observe sharpness

**Expected behavior:**

Preserve sharpness

**Actual behavior:**

Blurry

**Reproduces how often:**

Everytime

### Versions

Windows 10 Latest
Atom Latest

Edit: As a temp fix I set `.tree-view` z-index to 12px and I just won't resize the sidebar I guess.
