### ISSUE TITLE
text-rendering: optimizeLegibility causes erratic caret behaviour

### ISSUE THREAD

**Issue by CaptainHayashi** [atom/atom#2622]
Hi all,

If I apply the ‘text-rendering: optimizeLegibility’ directive to the stylesheets on .editor or .workspace, any subsequent command palettes, text fields or tabs have a visually broken/erratic caret:

* In text fields, such as the command palette or settings view, the caret appears before the first character even though it's actually pointing to the end of the text;
* Moving the caret left and right in an editor tab sometimes causes it to jump several places left and right of where it should be, there doesn't seem to be any discernible pattern and reloading the tab causes different breakages to happen.

This issue only affects new tabs/palettes created after the stylesheet change occurs, it seems.  Similarly, removing the stylesheet change only takes effect for new tabs/palettes.

I'm running Atom HEAD on Gentoo Linux, 64-bit, not using the react editor.

Not sure which part of Atom this applies to, so I've filed it against atom/atom (sorry!)

**Comment by stuartcarnie** [comment]
It can be reproduced when using the [hasklig font](https://github.com/i-tu/Hasklig) as per the following gif.

![atom-caret](https://cloud.githubusercontent.com/assets/52852/7432699/20681ad4-efdf-11e4-8c98-3bac96c0b9f8.gif)

My `style.less` is:

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

.editor {
  text-rendering: optimizeLegibility; 
}

.editor .cursor {

}
```
