### ISSUE TITLE
CSS ::selection doesn't have an effect

### ISSUE THREAD

**Issue by tollus** [atom/atom#3249]
I was trying to emulate the option `"draw_white_space": "selection"` from Sublime Text by using the CSS below, but it seems to have no effect.

What it should do, is only show the invisible characters when highlighted/selected.

``` css
.editor {
    .invisible-character {
        opacity: 0;
    }

    .invisible-character::selection {
        opacity: 1;
    }
}
```

Forgot to include a link to MDN, which does say it's non-standard, but that Chrome supports it.
https://developer.mozilla.org/en-US/docs/Web/CSS/::selection
