### ISSUE TITLE
Cursor position disappears when window loses focus

### ISSUE THREAD

**Issue by danielbarbarito** [atom/atom#3622]
I'm on Ubuntu 14.04 and every time I alt+tab or make Atom lose focus in any way, the cursor position disappears.  I have to click on the window to make it reappear.

**Comment by puszczyk** [comment]
@klaszlo @kevinsawicki  on xubuntu 12.04 I can reproduce it with alt + tab. To reproduce:
1. Use alt + tab to switch to next window
2. Use alt + tab to switch back to atom

Cursor is no longer there. If I start typing the letters appear, but the cursor is not there. The same with arrows. A "fix" is to click somewhere in the window or press ctrl + shift + p and then escape.

**Comment by LinuCC** [comment]
same Problem.
Atom 0.169.0, Arch Linux + awesomewm
Any Function that changes the focused window will result in the Cursor disappearing.
Interesting to note: If atom regains focus, the cursor flashes for around 0.2s.
This is also the case when the cursor previously already disappeared. 
It always flashes up, then disappears.

**Comment by cmtonkinson** [comment]
Reproduced with Atom 0.174.0 on Arch Linux.

**Comment by artiifix** [comment]
I'm having the same issue (Atom `0.174.0` on Arch Linux with i3 WM `4.8`):
When Atom loses focus (I usually press a key combination to switch between windows) and I move the mouse afterwards, then when I switch back to Atom, the cursor disappears until I click the editor. But I can still move the cursor around using the keyboard.
The following workaround makes the cursor show even if Atom isn't focused (put it in your `styles.less`):
```less
atom-text-editor::shadow .cursor {
  opacity: 1;
}
```

**Comment by cmtonkinson** [comment]
Nice workaround @artiifix. At least we've got a stop-gap until the underlying problem is addressed.

**Comment by muchweb** [comment]
Related: https://github.com/atom/atom/issues/5318

**Comment by chrippa** [comment]
@artiifix's workaround works great for the regular cursor, but this issue also causes vim-mode's command mode cursor to disappear. Here is a workaround for vim-mode aswell:

```less

atom-text-editor.vim-mode.command-mode,
atom-text-editor.vim-mode.operator-pending-mode,
atom-text-editor.vim-mode.visual-mode,
{
    &::shadow, &
    {
        .cursor, .cursor.blink-off {
            visibility: visible;
        }
    }
}
```

**Comment by deiwin** [comment]
:+1: Have this on arch with i3wm as well.

Thanks @chrippa for the vim-mode workaround.

**Comment by benkaiser** [comment]
Issue occurs for my on Arch with i3wm (using Alt as modkey).

The workaround from @artiifix works for the time being.

**Comment by yaph** [comment]
Thanks @artiifix! This makes working with atom a lot better.

**Comment by arzeth** [comment]
Thanks @artiifix !
I am on Arch Linux with i3 WM (version 4.8-168-gd5ec59e (2015-02-22)) too.

Also I use Atom Light theme. After window loses focusing, active line's background (yellow) is disappearing. So I fixed it with
```less
atom-text-editor::shadow {
    .line-number.cursor-line-no-selection,
    .line.cursor-line {
        background-color: rgba(255, 255, 134, 0.34);
    }
}
```
P.S. It is very stupid that the cursor is supposed to be seen only when window is focused, because developers often have more than one window at display and it is uncomfortable to switch between windows just to see which last line you have been editing.
