### ISSUE TITLE
Font too small on QHD screen

### ISSUE THREAD

**Issue by jcarmena** [atom/atom#3636]
Hello, I am running Atom (or trying it) on Linux (Xubuntu 14.04.1 64b) with a QHD screen. The problem is that GUI fonts are too small to work with it.

![sshot](https://cloud.githubusercontent.com/assets/189494/4413993/cafefef8-450e-11e4-9a9f-ed350d7d5b8e.png)

Thanks

**Comment by jordanbtucker** [comment]
This seems to get everything I care about for now:

```less
html,
body,
.tree-view,
.status-bar,
.tab-bar .tab,
.settings-view .settings-panel label,
.settings-view .setting-description,
.form-control {
    font-size: 16px;
}
```
