### ISSUE TITLE
Left directory tree panel font size so small can not change and can't see clearly

### ISSUE THREAD

**Issue by netroby** [atom/atom#3792]
Left directory tree panel font size so small can not change and can't see clearly

**Comment by simurai** [comment]
To change __only__ the font size, you could add the following in your `styles.less`:

```less
.tree-view { font-size: 14px; }
```

If you also want to change the __space__ between the lines to make it more or less compact, you could add this:

```less
@tree-view-font-size: 14px;
@tree-view-line-height: 28px;

.tree-view {
  font-size: @tree-view-font-size;

  .list-group li:not(.list-nested-item),
  .list-tree li:not(.list-nested-item),
  .list-group li.list-nested-item > .list-item,
  .list-tree li.list-nested-item > .list-item {
    line-height: @tree-view-line-height;
  }
  .list-group .selected::before,
  .list-tree .selected::before {
    height: @tree-view-line-height;
  }
}
```

And then play around with the values till you like it.
