### ISSUE TITLE
Custom element specificity isn't directly replaceable for class-based styles

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#4058]
cc @nathansobo 

I've been playing around with migrating various things to use the new custom elements where possible. The only thing I've been able to repro 100% so far is stuff in `styles.less`. I'll add more to this Issue as I find 100% repros.

For example, this conversion seems to work. Old:

``` LESS
.workspace {
  font-family: 'Helvetica Neue', 'Lucida Grande', 'Segoe UI', sans-serif;
  -webkit-font-smoothing: subpixel-antialiased;
}
```

New:

``` LESS
atom-workspace {
  font-family: 'Helvetica Neue', 'Lucida Grande', 'Segoe UI', sans-serif;
  -webkit-font-smoothing: subpixel-antialiased;
}
```

But this one doesn't. Old:

``` LESS
.theme-soda-light-ui {
  @border-base: 4px;

  .editor {
    .gutter .line-number {
      border-left-width: @border-base;
      padding-left: @border-base + 7;

      &.git-line-added {
        padding-left: @border-base + 2;
      }

      &.git-line-modified {
        padding-left: @border-base + 2;
      }

      &.git-line-removed {
        padding-left: @border-base + 2;
      }
    }
  }
}
```

New:

``` LESS
.theme-soda-light-ui {
  @border-base: 4px;

  atom-text-editor {
    .gutter .line-number {
      border-left-width: @border-base;
      padding-left: @border-base + 7;

      &.git-line-added {
        padding-left: @border-base + 2;
      }

      &.git-line-modified {
        padding-left: @border-base + 2;
      }

      &.git-line-removed {
        padding-left: @border-base + 2;
      }
    }
  }
}
```

I assume that by changing from a class to an element name in the middle like that reduces its specificity so that it doesn't win out over `.editor .gutter .line-number.git-line-added` etc.
