### ISSUE TITLE
Indent guides are disconnected

### ISSUE THREAD

**Issue by mc10** [atom/atom#4279]
Indent guides do not connect to each other; they are separated by a small but noticeable blank. It'd be better if the lines were connected as one straight line.

**Comment by simurai** [comment]
I can reproduce this as well by increasing/decreasing Line Height in the settings. I think it happens in all themes, but you only see the dots if the line is semi transparent.

@thomasjo's suggestion seems to work fine. But maybe to limit side effects, it could be applied to just `.indent-guide` instead of any `<span>`.

```css
atom-text-editor::shadow .indent-guide {
  display: inline-block;
}
```
