### ISSUE TITLE
No way to create CSS animations for syntax elements in styles.less?

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#4590]
I'm probably getting something wrong because I haven't worked extensively enough with the Shadow DOM yet. But if you put this in your `styles.less`:

``` less
@keyframes pulsate {
  from {
    color: black;
  }

  to {
    color: #f33;
  }
}

.editor, atom-text-editor::shadow {
  .comment {
    font-style: normal;
    -webkit-animation: pulsate 1s infinite alternate;
  }
}
```

You get spooky pulsing comments with the Shadow DOM turned off and default-colored comments with the Shadow DOM turned on ... but you get un-italic comments in both cases.

/cc @nathansobo @simurai
