### ISSUE TITLE
New settings toggle switch style is non-obvious, especially for colorblind users and maybe in some cultures

### ISSUE THREAD

**Issue by danfuzz** [atom/atom#4932]
The new toggle switch style of checkbox strikes me as fairly ambiguous:

* Gray-vs-green excludes many colorblind people. (See image.)
* The icons *also* look like horizontal traffic lights. In Japan, notably, the *rightmost* light in a horizontal traffic light is the one that's red.

Despite being neither colorblind nor from a country with right-to-left traffic lights, I'd nonetheless appreciate a little more visual distinction between the two states of these switches.

![grey-checkboxes](https://cloud.githubusercontent.com/assets/1090235/5672481/8476612c-9745-11e4-9993-55c3d6ba3d9e.png)

[Reported on v0.169, running on OS X.]

**Comment by lee-dohm** [comment]
@simurai Thinking about the colorblindness issue, maybe if there was a `+` in the circle when enabled and a `-` when disabled? Or the standard power indication of `|` and `O` on each end?

**Comment by simurai** [comment]
I remember when iOS and Android started to use these kind of switches they had "on/off" labels inside, but in their latest version it's now just left/right (+ color) that indicates if a switch is on or off.

![screen shot 2015-01-09 at 12 15 54 pm](https://cloud.githubusercontent.com/assets/378023/5675112/35ad65a8-97fa-11e4-85a5-b300c8adba3b.png)

![screen shot 2015-01-09 at 12 15 14 pm](https://cloud.githubusercontent.com/assets/378023/5675114/3a705884-97fa-11e4-8441-b95e2e3c5153.png)

So maybe by now they are enough understood? I think on iOS you can enable an accessibility feature where it adds the `I O` icons.

Here the `I O` as toggle thumbs:

![toggles-io](https://cloud.githubusercontent.com/assets/378023/5675128/781b15de-97fa-11e4-80b1-6853689213bd.png)

But not sure if it's easier to understand at a glance.

**Comment by lee-dohm** [comment]
Relevant screenshot

**Comment by lee-dohm** [comment]
Or not ... here it is ...

![image1](https://cloud.githubusercontent.com/assets/1038121/5675242/302755c6-976e-11e4-8462-1462e526e110.PNG)

**Comment by simurai** [comment]
@lee-dohm Yes, that's it.

**Comment by simurai** [comment]
Another option: Creating a separate theme that is optimized for color blind people. Next to the toggles, it would make sure there is enough contrast and maybe adding patterns to backgrounds. Sometimes use labels and for the git diff it would use icons instead of colored text, like currently the Unity theme does:

![screen shot 2015-01-09 at 1 25 52 pm](https://cloud.githubusercontent.com/assets/378023/5675510/2991c4f4-9803-11e4-87e4-f3cac975b0fa.png)

**Comment by mark-hahn** [comment]
>  Creating a separate theme that is optimized for color blind people.

It's not just for color-blind.  My vision isn't great.  But I'd never be
happy being forced to use a single theme.  IMHO everything should be
obvious in all places  These are supposed to be functional tools, not art
masterpieces.  We aren't Apple.  (grin)

**Comment by YuriSolovyov** [comment]
Why not just plain (but themed) checkboxes?
What can me more obvious?

![](http://kintek.com.au/assets/android_check_box.jpg)

**Comment by danfuzz** [comment]
FWIW, though it's never going to be possible to cover *everyone* with a single design, I think it's possible to get fairly wide coverage without sacrificing design aesthetics (as already demonstrated in previous comments). It's great if the remainder can be helped out with custom themes, but I think it would be a shame not to minimize the ghettoization of those in sensory or cultural minorities.

Thanks to the core team for your consideration!

**Comment by simurai** [comment]
Alright, tried to make checkboxes that adapt to each theme. Here a couple examples:

![screen shot 2015-01-10 at 3 39 20 pm](https://cloud.githubusercontent.com/assets/378023/5690690/769e3ffc-98df-11e4-8016-4f0b89b23fcf.png)
![screen shot 2015-01-10 at 3 36 02 pm](https://cloud.githubusercontent.com/assets/378023/5690691/76a2501a-98df-11e4-8dd5-241323e16592.png)
![screen shot 2015-01-10 at 3 38 57 pm](https://cloud.githubusercontent.com/assets/378023/5690692/76a4d150-98df-11e4-9f9f-14d1486f86ed.png)
![screen shot 2015-01-10 at 3 37 02 pm](https://cloud.githubusercontent.com/assets/378023/5690693/76aa3a0a-98df-11e4-949f-993cfead778b.png)

Better? Actually, they are already pushed to master, but there is probably still 2-3 days left till the next update.

**Comment by YuriSolovyov** [comment]
looks good enough

**Comment by 50Wliu** [comment]
I'd prefer checkboxes as well :).  Looks nice.

**Comment by lee-dohm** [comment]
I prefer the toggles, personally. I may experiment with making a package that just changes the checkboxes to toggles.

**Comment by simurai** [comment]
@lee-dohm I prefer the toggles too, but I also understand the accessibility concerns.

In case you need the CSS for the toggles, this should work (in most themes):

```less

.settings-view {

  .checkbox {
    font-size: 13px;
    padding-left: 3.5em;
  }
  input[type="checkbox"] {
    -webkit-appearance: none;
    display: inline-block;
    position: relative;
    font-size: inherit;
    margin: 0 0 0 -3.5em;
    width: 2.8em;
    height: 1.4em;
    cursor: pointer;
    outline: 0;
    border-radius: 2em;
    background-color: @text-color-subtle;
    transition: background-color 0.2s cubic-bezier(0.5, 0.15, 0.2, 1);
    &:focus:before {
      background-color: @text-color-selected;
    }
    &:active {
      box-shadow: none;
    }
    &:before {
      content: "";
      position: absolute;
      box-sizing: border-box;
      display: inline-block;
      left: 0;
      margin: 0;
      width: 1.4em;
      height: inherit;
      border-radius: inherit;
      border: 4px solid transparent;
      background-clip: content-box;
      background-color: @base-background-color;
      transition: transform 0.2s cubic-bezier(0.5, 0.15, 0.2, 1);
    }
    &:checked {
      background-color: @background-color-success;
    }
    &:checked:before {
      transform: translate3d(100%, 0, 0);
    }
    // override checkbox
    &:before {
      top: 0;
      opacity: 1;
      transform: none;
    }
    &:after {
      content: none;
    }
  }
}
```
