### ISSUE TITLE
`.editor-colors, :host` doesn't seem to work in user stylesheet

### ISSUE THREAD

**Issue by Dashed** [atom/atom#4984]
After upgrading to `Version 0.169.0 (0.169.0)`, in my user stylesheet, this used to work:
```css
.editor-colors, :host {
    background-color: #222222;
}
```

Do I now have to do this?

```css
.editor{
    background:#222;
}
```

**Comment by benogle** [comment]
This is because of the shadow DOM. 

`:host` doesnt work because your user stylesheet is not loaded into the text editor. 

I think `atom-text-editor::shadow .editor` would be the right selector to style the background color. @nathansobo would know more. Also check out https://atom.io/docs/latest/upgrading/upgrading-your-ui-theme

**Comment by nathansobo** [comment]
Yeah, the user style sheet is outside of the text editor, so to set the background color you would need to use

```css
atom-text-editor {
  background-color: #222;
}
```

If you want to style contents, you need to puncture the shadow DOM boundary:

```css
atom-text-editor::shadow .gutter {
  background-color: #333;
}
```

Please reopen if you have further problems and I'll try to help you out.

**Comment by Dashed** [comment]
Thanks this works. 

I'm not that intimately familiar with how shadow DOM works; and probably need help to ensure I migrate my user stylesheet to support this new change. Should I be posting on the Atom forums?

----

I'm asking, because the following seems to make a grammar capture in a `less` file to flicker:
```less
atom-text-editor::shadow .cursor {
    // softer blink
    // http://qrohlf.com/posts/atom-initial-impressions/
    transition: opacity .3s;
}
```
![flicker](https://cloud.githubusercontent.com/assets/139499/5713496/119aaae8-9a8b-11e4-901c-56fdf894b16a.gif)

I'm using this syntax theme: https://github.com/kevinsawicki/monokai

It's barely noticeable in Atom Dark syntax theme.
