### ISSUE TITLE
how to change font-size of sidebar

### ISSUE THREAD

**Issue by carloscarcamo** [atom/atom#5246]
Hi!

I was trying to change the font-size of the sidebar but I couldn't found how to do it, I have changed the font-size in preferences->settings but the side bar font still the same, how can I change the font-size of sidebar? 

thanks in advance!

**Comment by simurai** [comment]
@carloscarcamo Right, the font-size in the settings only changes what's inside the text editor. If you only want to change the font-size of the sidebar (tree-view), you could open `Menu > Atom > Open Your Stylesheet` and then paste:

```css
.tree-view {
  font-size: 14px;
}
```

You can't go too large since the line-height is fixed, but a couple px more than the default should be fine.

/related: #4342

**Comment by simurai** [comment]
Gonna close this issue, feel free to ask again, if it didn't help.

**Comment by carloscarcamo** [comment]
excellent, it works great, thanks for your help :)

**Comment by j5v** [comment]
Line-height can be overridden also. e.g. for a compact view, try:
```CSS
.tree-view {
  font-size: 12px;
}
li.file.entry.list-item, .list-tree li.list-nested-item > .list-item {
  line-height: 18px;
}
```
