### ISSUE TITLE
unable to change font size in "find in project"

### ISSUE THREAD

**Issue by askalski** [atom/atom#5498]
Hi,

I was able to change font sizes everywhere else by changing style.less file, but not in "find in project" menu, nor in it's results.

What are the css selectors for these items, or how else can these be modified?

Kindest Regards

**Comment by simurai** [comment]
This works for me to change the results:

```less
.preview-pane {
  font-size: 14px;
}
.panel-heading {
  font-size: inherit;
}
```

![screen shot 2015-02-11 at 11 20 11 pm](https://cloud.githubusercontent.com/assets/378023/6148403/94db49e6-b244-11e4-915d-fa1e73ad5fd3.png)

And with "find in project" menu, do you mean the panel at the bottom? Maybe try this:

```less
.project-find {
  font-size: 14px;
  atom-text-editor[mini] {
    font-size: 18px;
  }
}
```

![screen shot 2015-02-11 at 11 24 04 pm](https://cloud.githubusercontent.com/assets/378023/6148481/31d0a836-b245-11e4-9e6d-4f57cc578cc4.png)

I'll close this issue, but feel free to ask again if it didn't solve it for you.
