### ISSUE TITLE
Config settings not working.

### ISSUE THREAD

**Issue by JamesGould123** [atom/atom#5604]
[In the docs](https://atom.io/docs/api/v0.179.0/Config), various examples of settings you can set for packages are documented. Unfortunately, several of the examples do not work.

The given array and object examples do not work. The array example simply does not show up under the settings under packages > package-name > settings, and the object example throws the error:

<code>package-name.someSetting.myChildIntOption' could not set the default. Attempted default: undefined; Schema: {"type":"integer","minimum":1.5,"maximum":11.5}</code>

I'm using version 0.177.0 of atom on Windows 7.

**Comment by izuzak** [comment]
@JamesGould123 I'm able to reproduce the problem with the array example -- I don't see anything in the settings when I use that either:

![screen shot 2015-02-18 at 12 44 09](https://cloud.githubusercontent.com/assets/38924/6246820/3e1d99c8-b76d-11e4-8797-a3c71641e77f.png)

However, if I use this, I see the expected result:

```
config:
  someSetting:
    type: 'array'
    default: ["1", "2", "3"]
```

I'm unable to reproduce the problem with the object example though -- it doesn't throw an exception on Atom 0.180.0. Can you try reproducing on Atom 0.180.0 and let us know if it throws an exception? However, I don't see anything for that example in the settings view either.  I do see something if I use something like this:

```
config:
  someSetting:
    type: 'object'
    properties:
      myChildIntOption:
        type: 'string'
        default: 'foo'
```

My guess is that this is a problem in the Settings View package, not in the examples. So I'm going to move this over to the Settings View package and cc @thedaniel and @benogle.
