### ISSUE TITLE
Change the size of font on atom settings / label Description

### ISSUE THREAD

**Issue by a-moses** [atom/atom#5606]
atom setting :  the font size  don't Customizable.

and looks very small and not clearly.

especially the Description labels

**Comment by mark-hahn** [comment]
Everything in Atom is customizable.  Just find the CSS selector of the
element(s) you want to change and then put new LESS (CSS) code in your
`~/.atom/styles.less` file.

**Comment by muchweb** [comment]
@a-moses, try adding this to your `~/.atom/styles.less`

```css
.tree-view,
.tab-bar .title {
    font-size: 150%;
}
```

**Comment by a-moses** [comment]
Thanks @mark-hahn  @muchweb 

i need help to change  the class "setting-description" inside  block

how i change the Relative to force the description looks larger but keep block looks "nice and clean "

.setting-description don't work and bad idea .

**Comment by simurai** [comment]
To only change the `.setting-description`, this should work:

```css
.settings-view .setting-description {
  font-size: 14px;
}
```
