### ISSUE TITLE
[v0.184.0] @syntax-text-color has wrong value

### ISSUE THREAD

**Issue by xlaywan** [atom/atom#5770]
When i use @syntax-text-color in my stylesheet or in package stylesheet it is `#333333` but for monokai syntax theme it should be `#F8F8F2`.

Changing the either UI or syntax theme doesn't change its value.

**Comment by simurai** [comment]
@xlaywan It seems like the `#333333` comes from the "fallback" `@syntax-text-color`: https://github.com/atom/atom/blob/master/static/variables/syntax-variables.less#L5

Where are you trying to use the `@syntax-text-color` variable? In a theme or in your `styles.less`? You probably need to first import monokai's syntax variables before you can use them:

```less
@import "syntax-variables";
.my-class {
  color: @syntax-text-color;
}
```
