### ISSUE TITLE
Default CSS for `<progress>` element causes CPU to spike.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#6646]
This is on OS X, version 10.10.3 (Yosemite).

As shown in the animated GIF, enabling the following CSS style (which is present for `<progress>` elements) causes the CPU usage to spike:

```css
-webkit-animation: animate-stripes 5s linear infinite;
```

From the Chrome profiling tools, you can see that all of the `<progress>` elements are being redrawn continuously while this CSS is being applied. Once it is removed, the CPU usage goes back down to zero and the redraw ends.

Outright removing this style only affects the display of indeterminate progress bars, as they appear to be designed to have a "barber poll" animation.

Something should be done so that package developers who introduce the use of a `<progress>` element do not inadvertently burn CPU.

![progress-causes-cpu-spike](https://cloud.githubusercontent.com/assets/655869/7463670/3f5f18d2-f270-11e4-8d12-886ab9b90829.gif)

**Comment by simurai** [comment]
I think the problem is that when adding a `<progress>` the animation runs forever and updates `background-position` which causes repaints.

Something that might help:

1. Only run the animation when there is no value. Or maybe package authors have to explicitly add a class.. like `.is-buffering` to trigger an animation.
2. Try to use `transform`s instead of `background-position` so it doesn't need constant repaints.

**Comment by braver** [comment]
I was curious if *not* styling the progress bar would be better. Turns out it may be even worse.

![screen shot 2015-05-05 at 21 31 41](https://cloud.githubusercontent.com/assets/2543659/7481145/3f0472fc-f36e-11e4-8f5f-e4ea2ee0b69a.png)

I did notice that the transform:rotate based spinners I use in isotope don't trigger repaints while the default gifs do, although I don't see a difference in CPU usage. There should be a cheap way to make an indeterminate bar. Also, this: http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

**Comment by braver** [comment]
> Try to use the :indeterminate pseudo selector instead of running the animation by default and removing it on [value]

You can style the animation on `:not([value])`, that accomplishes the same.

> Try to use transforms instead of background-position so it doesn't need constant repaints.

I tried that but it doesn't change as much as I'd hoped re: repaints or cpu usage. Perhaps I'm missing something?
![screen shot 2015-05-05 at 22 19 35](https://cloud.githubusercontent.com/assets/2543659/7482022/d9e647f4-f374-11e4-9d35-03e060e2f689.png)

```less
@-webkit-keyframes animate {
  0% {-webkit-transform: translate(-50%);}
  100% {-webkit-transform: translate(0);}
}
progress {
  position: relative;
  -webkit-appearance: none;
  height: @progress-height;
  border-radius: @progress-height;
  overflow: hidden;
  background-color: @level-3-bg;
  border: 1px solid @stroke;
  &:after {
    content: '';
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    width: 200%;
    height: @progress-height - 2px;
    -webkit-animation: animate 5s alternate ease-in-out infinite;
    background-image:
       linear-gradient(-45deg, transparent 33%, @progress-buffer-color 33%,
       @progress-buffer-color 66%, transparent 66%);
    background-size: 24px @progress-height, 100% 100%, 100% 100%;
    border-radius: @progress-height;
  }
}
```

**Comment by simurai** [comment]
As a test, I tried to *just* animate a `<div>`, like http://codepen.io/simurai/pen/de9522d286f3167c6eebd070060bcc02?editors=110 and CPU still spikes. Not a lot, but still too much for something that potentially runs infinitely.

I guess the problem is that if a package just drops a `<progress>` and for some reason, never adds a `value`, the animation will keep going forever. That progress might not even be visible. So here a couple options I can think of:

1. Remove the animation
2. Remove the animation by default, but keep it as opt-in. Like packages would need to add an `is-buffering` class or so.
3. Use a `steps()` animation. It would be more like a blinking, like once a seconds and not 60fps.
4. Not use an `infinite` iteration-count, maybe animate just for 10min or so. If a value isn't set till then, the animation would stop.

**Comment by braver** [comment]
4 sounds good to me. Really, if a progress has no value for more than like 20 seconds I'd consider it hung anyway. Just drop the animation after a sensible period, that's better than draining a battery for no reason.

**Comment by simurai** [comment]
Ok, this is super odd.

I thought yesterday only the buffering progress was an issue, but today also the ones with a `value` keep repainting forever. I can't get the green repaint border to disappear, even when no animation is used. The only way is to manually change the value attribute in the DevTools.

Hmmm.. does the `<progress>` element use some kind of internal animation (requestAnimationFrame?) that is hard to stop? If so maybe Atom needs a custom progress component with performance in mind.

**Comment by simurai** [comment]
After some more testing: It's really random and depends on the environment. There is no repainting on a `<progress>` with a value if:

- the progress section in the Styleguide is collapsed when reloading and then expanded.
- Or when the tree-view is hidden but the section is not collapsed.
- Or when `atom-pane-container atom-pane .item-views` is changed from `display: flex` to `display: block`. Or `<progress>

**Comment by simurai** [comment]
> 4 sounds good to me.

ok, yeah.. let's do that, regardless of the repainting issue above.

**Comment by simurai** [comment]
Closing this. The core + some community themes should get some fixes.

If the repainting/CPU spike still happens in certain packages, feel free to comment again. As seen above, it can depend on where the `<progress>` gets added.

**Comment by ssorallen** [comment]
Adding `-webkit-appearance: none;` removes the constant repainting for me. From that point, there are pseudo-selectors you can use to style the progress element. This post outlines them well: https://css-tricks.com/html5-progress-element/

Disabling the animation entirely might work, but it's an inexact solution.

**Comment by ssorallen** [comment]
An opt-in `animated` class like Boostrap's [progress class](http://getbootstrap.com/components/#progress-animated) uses seems like the best alternative to me. 6 seconds is arbitrary, and it doesn't give a user of the `<progress>` a possibility to keep it running.

Also, adding `transform: translate3d(0, 0, 0);` on `progress` puts it into its own rendering layer and ensures the continuous repainting is scoped only to that box. It seemed to reduce CPU usage 20% relative to not forcing it into its own layer.

**Comment by simurai** [comment]
> An opt-in animated class like Boostrap's progress class uses seems like the best alternative to me.

Opt-in would be great, but currently there is no official "progress" component in Atom. It's up to themes to decide if they wanna restyle the native `<progress>` element. Adding a "progress" component like Bootstrap's is a good idea. We should look into that. :+1: 

> 6 seconds is arbitrary, and it doesn't give a user of the <progress> a possibility to keep it running.

A package author could keep the animation running forever with:

```less
.my-package progress:indeterminate {
  -webkit-animation-iteration-count: infinite;
}
```

Having a certain limit by default just avoids the risk of adding a `<progress>` and then forgetting to remove it. Or when it just gets hidden with opacity or so.

> Also, adding transform: translate3d(0, 0, 0); on progress puts it into its own rendering layer and ensures the continuous repainting is scoped only to that box. It seemed to reduce CPU usage 20% relative to not forcing it into its own layer.

AFAIK, forcing an own layer is good for animating `transform` and `opacity`, but not when there are repaints needed. Otherwise there will be `repaint > push texture to GPU > repaint > push texture to GPU etc.` and start to fill up memory. Maybe changing the design could be considered to remove the need for repaints.
