### ISSUE TITLE
Show invisibles only when selecting text

### ISSUE THREAD

**Issue by alexrussell** [atom/atom#6669]
I tried searching for a similar issue here and I didn't find anything that directly addresses what I want, though #3249 (which I have subscribed to) is what I want, just asked for in a very roundabout way.

In short: we should have an option to only display invisibles within a selection. Showing them all the time is too noisy, not showing them at all loses their power, and turning them off and on when I want to see them is annoying. I'm aware that with CSS we cannot achieve what is required (hence unresolved #3249, and accompanying [forum post](https://discuss.atom.io/t/atom-is-so-powerful-that-it-blows-my-mind/294/17?)) due to the underlayer controlling the background highlight. So this will presumably be something that atom must provide from within the core.

If this request appeals more as something that's more generic (and allow us to achieve what we want with CSS) you could actually just attach a `.selected` class to all elements (scopes) that are within the selection (obviously a selection part-way through an element will require an inner span injected with just the `.selected` class). This way, we can do what we want in regards to the invisibles, but package developers may find interesting ways to use this selection class/scope for other purposes.

**Comment by tomalec** [comment]
:+1:

**Comment by multiwebinc** [comment]
Who says it's not possible with CSS? http://jsfiddle.net/afk5egLz/

**Comment by alexrussell** [comment]
Now try that in Atom and let me know how well it works.

**Comment by elektronik2k5** [comment]
+1 for this feature

**Comment by hull-aaron** [comment]
+1. Should be a standard feature. (I need a quick way to find out if my tabs are tabs or spaces, but I don't want to see that stuff constantly)

**Comment by brandonk3nt** [comment]
another +1

**Comment by Jayflux** [comment]
+1 for this, i really like how sublime does it, is it possible for us to add this?

**Comment by teaman** [comment]
+1 for this feature. I too liked ST3 for that feature.

**Comment by mattdarveniza** [comment]
It can be sort of achieved with CSS but it's still rather hacky. Would love to see this built into a plugin.

**Comment by elektronik2k5** [comment]
@mattdarveniza please share how you did it!

**Comment by mattdarveniza** [comment]
@elektronik2k5 The trick is to set the invisibles to the same color as the background, then when the invisibles are highlighted you'll be able to see them contrasted against the color of the highlighted area.

The code that worked for me using the one-dark theme, settings may vary with different themes:
```less
  .invisible-character {
    // Set invisible-characters to same as background color
    color: @base-background-color;
  }

  .cursor-line .invisible-character {
    // Set invisiable characters on current line to highlight line color
    color: @background-color-highlight;
  }

  .invisible-character.indent-guide {
    // Reset box shadow on indent guides as by defualt it inherits color from
    // main color attribute.
    box-shadow: inset 1px 0 @background-color-selected;
  }
```

Which comes out looking like
![screen shot 2016-02-16 at 11 07 34 am](https://cloud.githubusercontent.com/assets/946261/13063576/9c944648-d49d-11e5-8560-547961e5f66a.png)

It isn't perfect, as you can't set the invisible's highlight color to anything with more contrast, and there's something weird going on with the indent guides being off by one pixel, but better than nothing.

**Comment by joenil** [comment]
+1, expect for this feature

**Comment by romanxbanks** [comment]
+1
2016, omg...

**Comment by billdami** [comment]
+1

**Comment by sobolevn** [comment]
+1

**Comment by sanylcs** [comment]
+1

**Comment by alexmcmillan** [comment]
+1

**Comment by chl1996** [comment]
👍

**Comment by kdrewgonzales** [comment]
pls

**Comment by mahesamelba** [comment]
We can show that in Settings but on load (the entire file). Not just when selecting the rows. Go to Settings -> check Show Invisibles checkbox.

**Comment by nckswt** [comment]
+1

**Comment by codenot** [comment]
+1

**Comment by nckswt** [comment]
+1

**Comment by agentfitz** [comment]
+1

**Comment by eternal-sorrow** [comment]
+1

**Comment by mattfysh** [comment]
+1

**Comment by thebarty** [comment]
Yeah - that would be so cool!!! Simply having a checkbox in "Settings > Editor > Show Invisibles in Selection" would be awesome! This is a feature I really miss coming from ST3

**Comment by tagrudev** [comment]
+1 for that, I lost 1 hour today due this ...

**Comment by dizlexik** [comment]
Definitely +1, but for now I'm working around this by making invisible characters very faint with this:
```css
atom-text-editor::shadow .invisible-character { color: rgba(100, 100, 100, 0.25) }
```

**Comment by alexmcmillan** [comment]
I still find the extra noise irritating so have moved back to Sublime.  The extra screen cruft is simply too distracting.  Will try Atom again if this gets fixed.

**Comment by mattdarveniza** [comment]
@thebarty that's fine for your individual case, but I think you'll find there are a heap of people who don't find this an acceptable solution, regardless of theme or how subtle they are. It makes the screen much noisier, for things that I only want to see under very certain contexts.

**Comment by ylihao** [comment]
+1

**Comment by cprogrammer1994** [comment]
+1

**Comment by konstantin24121** [comment]
+1

**Comment by benface** [comment]
+1

**Comment by NikitaVlaznev** [comment]
+1

**Comment by j-f1** [comment]
Please use the 👍 reaction on the first comment instead of commenting “+1.” Several people get an email for each comment posted here.

**Comment by alexmcmillan** [comment]
@j-f1 It's been 22 months.. I think all hope can be considered lost.  Our eyes are to be forever blinded by the visibility of invisibles.

**Comment by ackramer** [comment]
+1

**Comment by Izzur** [comment]
+1

**Comment by elektronik2k5** [comment]
![image](https://cloud.githubusercontent.com/assets/1078554/25383258/f4fd52bc-29c3-11e7-9b51-9bb339cbd6b8.png)
:(

**Comment by saxinte** [comment]
+1

**Comment by saxinte** [comment]
👍

**Comment by andremacola** [comment]
This is my current solution for now

```
/* Hack invisible indent current line and selection */
atom-text-editor {
	.indent-guide {
		color: #1A1E26;
	}
	.cursor-line .indent-guide {
		color: #4D5057;
		// background: rgba(255,255,255,.2);
	}
	.invisible-character.indent-guide {
		box-shadow: inset 1px 0 #373b41;
		// box-shadow: inset 1px 0 rgba(255,255,255,.1);
	}
	.cursor-line .invisible-character.indent-guide {
		box-shadow: none;
	}
}
```

![on-line](https://user-images.githubusercontent.com/3408809/29696369-f1ec2a84-891e-11e7-99b9-c9b4c10cbaf6.png)


![captura de tela 2017-08-24 as 22 52 02](https://user-images.githubusercontent.com/3408809/29696366-eb9768f6-891e-11e7-85c3-75d379311eea.png)

**Comment by Behoston** [comment]
+1

**Comment by paul-mesnilgrente** [comment]
+1
I just don't get why this enhancement has been ignored for so long.
I have just started using Atom, and I just want to go back to Sublime now.

**Comment by natanfelles** [comment]
https://discuss.atom.io/t/atom-is-so-powerful-that-it-blows-my-mind/294/26

```less
@import "syntax-variables";
atom-text-editor::shadow .invisible-character {
	color: @syntax-background-color;
}
```
![captura de tela de 2018-02-14 10-09-26](https://user-images.githubusercontent.com/3011423/36203589-32ab2da8-116f-11e8-89a4-52b7af113a37.png)

**Comment by alexrussell** [comment]
Better than nothing but still doesn't have *all* whitespace (i.e. in the middle of a line).

**Comment by ElectricPrism** [comment]
Am I wrong to conclude that this feature could be implemented by simly displaying line contents as 

display: inline-block;

As far as I can see it sounds like a CSS problem but I am unfamiliar with the specific construction methods inside the editor and if it differs from standard CSS.

**Comment by alexrussell** [comment]
Not exactly sure what you'd apply that style to, but yes, as I pointed out in the original post, if we could find a way to know which parts of the DOM had a selection, then yeah we can do whatever we want. The problem is (at least, at the time I posted this, was) that the selection is done on a separate layer entirely to all the syntax highlighting, so there was no way, in CSS, to select (as in CSS selectors) all DOM bits that were selected (as in text selected!).

**Comment by Ornataweaver** [comment]
Almost 2019!

**Comment by Ornataweaver** [comment]
https://discuss.atom.io/t/show-invisibles-only-in-selected-text/11644

**Comment by Ornataweaver** [comment]
Can someone make a package called "Sublime-like invisible characters"?

**Comment by Ornataweaver** [comment]
It's not only the invisibles, atom highlights lines to the end of the line. I don't like this at all. It's so confusing.

**Comment by willthemoor** [comment]
> Can someone make a package called "Sublime-like invisible characters"?

It's promoted as a "hackable text editor" for developers. Stuff a few lines of css in your application stylesheet and move on to important things?

1. Type `your stylesheet` into the command palette.
2. Paste the code below in there somewhere.
3. Optional: hack on it a bit to make it your own.
4. Save it.
5. Move on.

```less
/*
  Hide invisible characters. Show them when selected.
*/
atom-text-editor.editor {
  .invisible-character {
    // 1. Set invisbles to the theme's background color, hiding them.
    color: @syntax-background-color;

    // 2. "Show" them on the current line. 
    // Should work by default but just in case.
    .cursor-line & {
      color: @background-color-highlight;
    }
    // 2a. Or use this to hide them on the current line.
    .cursor-line & {
      color: transparent;
    }

    // 3. The indent guides becomes invisible in some themes.
    &.indent-guide {
      box-shadow: inset 1px 0 0 0 @syntax-indent-guide-color;
    }
  }

  // EXCEPT for trailing white space characters. We wanna see those.
  div.line:not(.cursor-line) { // <- but not while we're typing. :)
    .trailing-whitespace {
      background-color: @background-color-error;
      color: contrast(@background-color-error);
    }
  }
}
```

**Comment by trongthanh** [comment]
This may be not obvious for Atom newbies: @willthemoor  guide above works beautifully but you need to import some variables into user styles.less first:

```less
// Add below to top of the styles.less file
@import "syntax-variables";
```

**Comment by willthemoor** [comment]
Good catch @trongthanh, thank you. Added that bit to my comment.

**Comment by UziTech** [comment]
not stale

**Comment by kireerik** [comment]
Related workaround based on https://github.com/atom/atom/issues/6669#issuecomment-459509043:
- https://gist.github.com/justo/283e41b205e14bcba57b#gistcomment-3520466

**Comment by worldmaker18349276** [comment]
Setting invisibles to the background color in dark theme is very ugly.
My alternative solution is only showing invisibles at the cursor line and at the end:
```less
@import "syntax-variables";

atom-text-editor.editor {
  .line:not(.cursor-line) .invisible-character:not(.trailing-whitespace) {
    color: transparent;
  }
}
```
