### ISSUE TITLE
When in fullscreen mode, it should be possible to easily click on a tab

### ISSUE THREAD

**Issue by wil93** [atom/atom#6715]
The fullscreen mode must be active (<kbd>F11</kbd>), see this screenshot:

![screen](https://cloud.githubusercontent.com/assets/1285361/7552615/f8a561b4-f6be-11e4-963f-02efbb5f0efd.png)

The cursor is at the "uppermost pixel" of the screen, and the inactive tab is not hovered. However, if I lower it down a bit, then the tab becomes hovered.

I think that, when the fullscreen mode is active, the tab should be hovered even when the cursor is at the uppermost pixel (other apps behave this way, like gnome-terminal).

**Comment by steelbrain** [comment]
You might want to enable `always show topbar` or a similar feature from the settings menu

**Comment by Zireael07** [comment]
There IS a fullscreen mode by default?!

(shutting up now, just sayin')

**Comment by jerone** [comment]
For this to work you need to have the app in full-screen, have the main menu deactivated and don't have any other top panes (like [ToolBar](https://atom.io/packages/tool-bar)). I think you're better of changing your theme.

**Comment by MCluck90** [comment]
Adding this to your stylesheet should make it work.

```less
atom-workspace .tab-bar .tab:not(.active) {
    &:before {
        top: 0.4rem;
    }
    &:after {
        top: 0.4rem;
    }
    background-image: none;
    top: 0;
    height: 2.9rem;
    line-height: 2.9rem;
}
atom-workspace .tab-bar .tab.active .title {
    background-image: -webkit-linear-gradient(top, #343434, #222222);
}
atom-workspace .tab-bar .tab .title {
    background-image: -webkit-linear-gradient(top, #454545, #333333);
    height: 2.5rem;
    margin-top: 0.4rem;
}
```

Obviously you'll need to adjust the background to your liking and this doesn't limit it to only fullscreen.

**Comment by wil93** [comment]
Thanks @MCluck90, starting from your snippet I worked on a simpler version (which looks slightly better)

    atom-workspace .tab-bar {
      height: 32px;
    }

    atom-workspace .tab-bar .tab {
      top: 0px;
    }

**Comment by MCluck90** [comment]
Awesome, I dig it. :+1:

**Comment by wil93** [comment]
Nitpick: 31px is the correct value, instead of 32px (the difference was noticeable for the active tab). Also, I noticed that the style file is LESS instead of plain CSS, so this should be the final version:

```css
atom-workspace .tab-bar {
  height: 31px;

  .tab {
    top: 0px;
  }
}
```

Thanks again :smile:
