### ISSUE TITLE
overlay marker decorations go over tabs

### ISSUE THREAD

**Issue by willwhitney** [atom/atom#6857]
This is a problem experienced by packages like `autocomplete-plus` and `hydrogen`.

![screenshot 2015-05-19 11 31 41](https://cloud.githubusercontent.com/assets/597829/7706828/b3ba0614-fe1a-11e4-95dc-b88d4a11b7a7.png)

![screenshot 2015-05-19 11 34 38](https://cloud.githubusercontent.com/assets/597829/7706906/0da11c58-fe1b-11e4-8295-8db87ef897e3.png)

The default behavior should be for them to slide _under_ the tabs.

I'm not even sure if there's a way for a package to make its overlays go under the tabs. Anyone know?

**Comment by benogle** [comment]
I disagree, at least in the case of autocomplete-plus. The popover should show above everything else, tabs, tree-view, other panes, etc.

**Comment by willwhitney** [comment]
@benogle Totally agree with tree-view, other panes, etc. But autocomplete always shows _below_ the line you're typing on when you're near the top of the pane, right? So the only time that autocomplete can be on top of the tabs is if the line you're typing on is very much hidden already.

**Comment by willwhitney** [comment]
But more generally, is it even possible to make an overlay go under the tabs?

**Comment by simurai** [comment]
You could give the tab-bar a higher `z-index`:

```less
.tab-bar {
  z-index: 6;
}
```

But that should only be done on a user basis in `styles.less`. If we want to allow packages to decide if they are on top or not, we could do something like:

```less
.tree-view-resizer,
.tab-bar,
.status-bar {
  z-index: 2;
}

atom-overlay {
  z-index: 3;
}
```

By default, all overlays are highest, but then, if a package wants to go underneath, it could add this to its styles:

```less
atom-overlay.my-package {
  z-index: 1;
}
```
