### ISSUE TITLE
Text select not aligned with content

### ISSUE THREAD

**Issue by activatedgeek** [atom/atom#7224]
I am working with `Atom 0.208.0`. Text is not being highlighted properly. The alignment with the text seems to be off. Here is a screenshot.
![screen shot 2015-06-11 at 3 19 27 pm](https://cloud.githubusercontent.com/assets/3909933/8104325/8506f2b0-104d-11e5-99b8-46f05bd5db52.png)

Look at the `var` text above. I have the following packages installed over the core packages.
* [`atom-jade`](https://atom.io/packages/atom-jade)
* [`file-icons`](https://atom.io/packages/file-icons)
* [`react`](https://atom.io/packages/react)

Here is my stylesheet (nothing much, just one change):
```css
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

// style the background and foreground colors on the atom-text-editor-element
// itself
atom-text-editor {

}

// To style other content in the text editor's shadow DOM, use the ::shadow
// expression
atom-text-editor::shadow .cursor {

}

atom-text-editor::shadow .highlight.find-result .region {
  background: yellow;
}
```

Any ideas?
