### ISSUE TITLE
Tile Rendering  darkens Semi-Transparent Background Image Themes: Revisited.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7421]
Problem :

Tiles Rendered differently from atom-text-editor's background.
when semi-transparent is used.

![tile_rendering_prob](https://cloud.githubusercontent.com/assets/419606/8366368/7ec62524-1bba-11e5-82f7-1394c7f31c73.png)

So far , i've tried many way to make this work but still failing.
```
atom-text-editor,
:host{
  background-color: @app-background-color !important; 
}
```
Intended background-color is rgba(10,11,13,0.44)

on Tile areas background-color is  rgba(10, 11, 13, 0.439216);

I tried forcing like this but it can't help too.
```less
atom-text-editor,
.lines,:host{
 background-color:  @app-background-color !important;
 }

atom-text-editor,
.tile,:host{
  background-color:  @app-background-color  !important; 
}
```
I want rgba(10,11,13,0.44) for text editor background, every part of it.

may be our theme expert @simurai  can enlighten me ?

/cc @as-cii 

here is my theme

https://github.com/v3ss0n/steam-pirate-ui

this file:
https://github.com/v3ss0n/steam-pirate-ui/blob/master/styles/editor.less
