### ISSUE TITLE
List item height should not be based on @component-line-height

### ISSUE THREAD

**Issue by jgebhardt** [atom/atom#7559]
It seems that [some themes assign relative values](https://github.com/orderedlist/unity-ui/blob/master/styles/ui-variables.less#L61) rather than absolute pixel values to the `@component-line-height` LESS variable. This causes the selection highlight to break.

https://github.com/atom/atom/blob/master/static/lists.less#L37 assigns a `line-height` value to the `line-height` property, which seems like a bad idea since `line-height` accepts values that are not acceptable for the `height` property.

``` less
  .selected::before {
    content: '';
    background-color: @background-color-selected;
    position: absolute;
    left: 0;
    right: 0;
    height: @component-line-height;
  }
```
