### ISSUE TITLE
tree-view identation

### ISSUE THREAD

**Issue by maxguzenski** [atom/atom#7831]
This syntax color theme has "the power" to change tree-view indentation for files (margins/paddings) even not doing it.

https://github.com/saschaeggi/monokai-syntax-for-one-dark

to reproduce: change syntax theme and look to tree-view (having folders and files listed) 

```css
// monokai for one change this magically
// putting this on my styles.css fixed it
.list-tree.has-collapsable-children li.list-item {
  margin-left: 17px;
}
```
