### ISSUE TITLE
"Error compiling Less stylesheet:" after "Generate Syntax Theme"

### ISSUE THREAD

**Issue by keeev** [atom/atom#7951]
Hey, 

like [here](https://github.com/atom/atom/issues/6797) I get the same error message with Version 1.0.2: 

`
"Error compiling Less stylesheet: /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/stylesheets/select-list.less
Line number: 63
variable @tool-panel-border-color is undefined"`

And a few more: 

![error](https://cloud.githubusercontent.com/assets/246284/8757061/7e3ba3d0-2cd7-11e5-8bdb-a299530b6538.png)

![screen shot 2015-07-17 at 22 51 51](https://cloud.githubusercontent.com/assets/246284/8757184/862b844c-2cd8-11e5-9a18-41b92a069b66.png)

The weird thing is, there was no problem with the files before and I was able to work on the theme. But after I tried to create a Syntax Theme like it says in the Docs these Error Messages appeared and now I **can't use Atom anymore** because it won't let me open my Settings to use another UI- and Syntax-Theme. 

That's all I know about the problem right now, hope someone of you guys can reproduce it. I try to figure out what happened and will keep you updated. 

Thx in advance.

**Edit:**

It works with "--dev --safe". But I'm sure that's not the solution. ;)

**Comment by benogle** [comment]
Can you paste the `themes` value from your `config.cson` file? (`cmd-p` -> `open config file').

**Comment by keeev** [comment]
```css
"*":
  "exception-reporting":
    userId: "ab7201ad-d387-d7a0-b87a-905e0dfc115e"
  "release-notes":
    viewedVersion: "0.94.0"
  welcome:
    showOnStartup: false
  metrics:
    userId: "7c165154b6492767e8a87fc1ebcd47c3aef0f087"
  editor:
    showIndentGuide: true
    invisibles: {}
    autoIndent: false
  core:
    ignoredNames: [
      ".DS_Store"
    ]
    themes: [
      "blue-sea"
      "seti-syntax"
    ]
    audioBeep: false
    disabledPackages: [
      "jshint"
      "ascii-art"
    ]
  linter: {}
  "autocomplete-plus": {}
  emmet: {}
  "atom-ternjs": {}
  minimap: {}
  "atom-material-ui":
    disableAnimations: true

```

I changed the UI- and Syntax Theme back to Seti. Now I'm able to use Atom again for working on files but there's still another error: 

``
Failed to spawn command /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper. Make sure /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper is installed and on your PATH
``

Which leads again to Issue #7594.
