### ISSUE TITLE
Visual change to indicate when editor loses focus

### ISSUE THREAD

**Issue by eboracus** [atom/atom#8102]
I think there needs to be some visual clue when the editor pane has lost focus (eg. to the tree-view), particularly when some editor text is currently selected. Ordinarily if the editor loses focus the cursor disappears to give some indication, but when text is highlighted the cursor has already gone. If you now switch the focus to the tree-view there is no change in the editor appearance.

Highlighting then clicking on the tree-view taking focus away from the editor:
![editor_selected_text_focus](https://cloud.githubusercontent.com/assets/11758299/8920195/1c0eb884-34be-11e5-829f-5dea77d2bc05.gif)

I had a couple of issues when highlighting with the intention of deleting text, then clicking on the tree-view (expand a sub-folder or something minor without changing the active file), then having been distracted, coming back to press backspace to delete the text and nearly lost a file. :( (thankful for the confirm deletion dialog! :+1:)

**Comment by mnquintana** [comment]
@atom/feedback Do you think this should be handled in core, or on a theme-by-theme basis?

**Comment by batjko** [comment]
I think this should really be core behavior. 
Leaving it up to individual themes to implement makes it very inconsistent, breaking people's expectation whenever they change themes (especially if some of them don't even bother implementing it).

The text editor could be just ever so slightly dimmed, or perhaps the tree-view could be highlighted in a way that makes it more obvious that it is the active panel.

**Comment by lee-dohm** [comment]
The problem with expecting it to be in core is that it can still be overridden in themes ... which still makes it very inconsistent (or at least slightly less than very inconsistent). I think it is better if we rigorously document what expectations there are for themes.

**Comment by simurai** [comment]
It's probably not that easy to find a good default that works for most themes. Changing colors, adding borders etc. might already feel too intrusive. But adding a certain default could still educate theme authors since they have to override it if they don't like it.

Also there seems to be an issue where `:focus` has no effect on `.active` panes, see: https://github.com/atom/one-dark-ui/issues/75#issuecomment-106671648. Not sure if bug or intended.

**Comment by YuriSolovyov** [comment]
maybe it is possible to globally decrease saturation?

**Comment by batjko** [comment]
I think a dimmer (or indeed decreased saturation) might be both subtle and universal enough to request from (or enforce on) themes?

**Comment by mnquintana** [comment]
> The problem with expecting it to be in core is that it can still be overridden in themes ... which still makes it very inconsistent (or at least slightly less than very inconsistent).

Hell, themes have the power to break every single component in Atom if they really wanted to (even `/deep/` in the Shadow DOM :laughing:) – I think it would be reasonable to add a simple base style for indicating when the editor is blurred that theme authors could then choose to override if they really wanted to.

> I think it is better if we rigorously document what expectations there are for themes.

I think we should do this too, but I think we can also add a simple base style for this.

**Comment by batjko** [comment]
Omg, a dimming, desaturating blur when out of focus! I can see it in front of my spiritual eye.

**Comment by simurai** [comment]
Desaturating blur:

![focus](https://cloud.githubusercontent.com/assets/378023/8947542/2722d97a-35d7-11e5-9eba-45cdc1125975.gif)

```less
atom-text-editor:not([mini]) {
  -webkit-filter: saturate(.8) blur(2px);
  transition: -webkit-filter .32s;
  &.is-focused {
    -webkit-filter: none;
    transition-duration: .16s;
  }
}
```

maybe a bit too extreme. :grin: Also, using `filter` or `opacity` on the whole editor might cause performance issues.

**Comment by simurai** [comment]
Maybe it could be a layer on top that has a semi transparent background color like the editor. So it wouldn't mess with the editor itself:

![focus](https://cloud.githubusercontent.com/assets/378023/8947599/d3cbfcd8-35d7-11e5-9825-aa701110d22f.gif)

```less
atom-text-editor:not([mini]) {
  &::before {
    content: "";
    position: absolute;
    z-index: 1;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: inherit;
    opacity: .4;
    pointer-events: none;
    transition: opacity .32s;
  }
  &.is-focused::before {
    opacity: 0;
    transition-duration: .16s;
  }
}
```

Although if the editor loses focus, it doesn't necessarily mean you don't wanna read it. Like when previewing files in the tree-view or doing a search.

**Comment by mnquintana** [comment]
The desaturating blur is pretty cool-looking, but I meant blurred as in not focused, rather than blurred meaning a blur effect :laughing:.

I like the second option a lot though - maybe it could be a bit more subtle to not discourage reading as much?

**Comment by simurai** [comment]
Hehe.. yeah.. Just tried to do @batjko's "a dimming, desaturating blur when out of focus! "

The `opacity: .4;` could be tweaked, although if it's too subtle, it might be hard to tell if it's actually focused or not. For that reason I still prefer the pane markers in the One themes. Easy to spot and don't mess with the editor.

**Comment by batjko** [comment]
> The desaturating blur is pretty cool-looking, but I meant blurred as in not focused

Yes I know, but it put the image in my head ;)

@simurai I like the (actually) blurred version as well, although it is a bit slow on occasion it seems. 
I think the opacity version can't be too subtle or it misses the point of being obviously out of focus, you know?

**Comment by batjko** [comment]
Just tried reducing the blur to something less 'discouraging of reading':
```css
-webkit-filter: saturate(.9) blur(0.8px);
```

And that works pretty well for my purposes.

**Comment by YuriSolovyov** [comment]
I think desatuarting should be more agressive, @simurai did you tried just desaturating without blur? I think it is not the same as overlay.

**Comment by batjko** [comment]
If you desaturate too much though, you end up breaking the syntax theme visually:
![image](https://cloud.githubusercontent.com/assets/7287076/8952368/3e0c4a58-35ce-11e5-9939-a8956302dae9.png)
Looks off that way.

**Comment by YuriSolovyov** [comment]
maybe it is possible to deaturate only syntax/text without touching background?

**Comment by batjko** [comment]
I'm not sold on strong desaturation, to be honest. So far I like a subtle blur with a maximum of 10% desaturation the best.

But whatever the details, it's probably the nicer way to do it, compared to some blinking highlighting frame around the panes.

**Comment by thomasjo** [comment]
Changing the visual appearance of code based on focus is a bad idea. Blurring the text when out of focus is a truly horrible idea. How are we supposed to read code in an unfocused Atom instance if it's blurred?

Changing the chrome of the Atom window is fine, but do **not** touch the text editor elements themselves. That only leads to bad UX. What sensible editor changes the readability of code based on whether the window is focused or not?

**Comment by batjko** [comment]
@thomasjo I can see use cases where people might want to retain full readability while not focused, fair point.
Personally, I like it and will continue using @simurai's quick trick in the stylesheet until something better comes around. 

But I can see how it should at least not be mandatory in any way.

**Comment by thomasjo** [comment]
Why don't we focus (pun not intended) more on changing the appearance of the window/app chrome instead? I'm in favor of making it easy to distinguish when an Atom window has focus or not, as long as we don't touch the code itself.

I'll try a few experiments, and report back if I figure something out.

**Comment by thomasjo** [comment]
I don't think there's a good way of resolving this from core without killing usability while also not breaking any themes (I'm mostly concerned about community themes). Solving this at the theme level is trivial in comparison.

Quick and dirty proof of concept for `one-dark-ui`
``` less
@import "ui-variables";
@import "ui-mixins";

body.is-blurred {
  .tab-bar .tab {
    &:before {
      opacity: 0;
    }

    &.active .title {
      color: @tab-text-color;
    }
  }

  .tree-view {
    .list-item, .selected > .list-item {
      .text(subtle);
    }
  }
}
```

This obviously needs tweaking, placement in appropriate files and what not, but is suitable for concept testing since it can be pasted directly into `styles.less`. On the left is the active (and current) styles, and on the right you can see the visual effect when the window is unfocused

![focus](https://cloud.githubusercontent.com/assets/3622/8954565/c9e81026-35e6-11e5-9e95-1c436ebd29c2.png)

Instead of changing the text color in the tree-view, it might be better to simply tweak the opacity, e.g. replace the `.text(..)` mixin with `opacity: 0.6`.

**Comment by olmokramer** [comment]
@thomasjo, I think you're focusing too much on the window, while the issue is about the text editor which can be unfocused even if the window does have focus. I agree with you that the readability of code shouldn't be messed with. It would make working with split panes a pain, among other things.

An idea that popped into my head, for selections specifically: change their appearance from a solid block to an outline, see images below. It's subtle, but very noticable.

![text-editor-focused](https://cloud.githubusercontent.com/assets/3612514/8956653/5035540c-35f8-11e5-9814-34738bc93b9e.png)![text-editor-blurred](https://cloud.githubusercontent.com/assets/3612514/8956654/5037839e-35f8-11e5-8db2-094adc6249d5.png)

Left: focused editor. Right: blurred editor

```less
atom-text-editor:not(.is-focused)::shadow .highlights .region {
  background-color: transparent;
  border: 1px solid @syntax-selection-color;
}
```

One problem with this approach I can think of is that it's quite difficult to get this to work consistently across highlights from multiple packages. Another approach could be to reduce the opacity/saturation.

**Comment by thomasjo** [comment]
> I think you're focusing too much on the window, while the issue is about the text editor which can be unfocused even if the window does have focus.

Good call, I missed that part. Thanks for letting me know! That just makes it even more important to not destroying legibility.

**Comment by batjko** [comment]
> It would make working with split panes a pain, among other things.

Totally forgot about that. Good point. Blur and any other readability-reducing thing is definitely out the window with that one.

**Comment by eboracus** [comment]
I like the solid->outline approach, but certainly agree that could be confused with other outlines like `highlight-selected` and searches.

I've tried fading out only the selection and quite like the effect. Originally included the transition effect to match the duration when combining in tandem with the fading of the whole editor view... looked cool so I kept it (wouldn't have to be that way as standard). Not sure how to get the same transition on the fade back in with out having it _always_ behave like that when the focus is on :confused:

![editor_text_focus_fade](https://cloud.githubusercontent.com/assets/11758299/8968342/6bf733e0-3634-11e5-883a-09a313261beb.gif)

```less
atom-text-editor:not(.is-focused)::shadow .highlights .region {
  background-color: fadeout(@syntax-selection-color, 95%);
  transition-duration: .16s;
}
```

**Comment by simurai** [comment]
I guess the issue can be narrowed down to:

> particularly when some editor text is currently selected. Ordinarily if the editor loses focus the cursor disappears to give some indication, but when text is highlighted the cursor has already gone.

Removing the selection on blur might be ok, just like the cursor. Unless there are situations where you still want to see the selection in blurred editors? Are there any?

Here a selection with borders that get removed when blurred:

![focus](https://cloud.githubusercontent.com/assets/378023/8975442/65fd6844-36b9-11e5-8630-5452bd8acfae.gif)

```less
atom-text-editor.is-focused::shadow .highlights .selection .region {
  box-sizing: border-box;
  border-left: 2px solid @syntax-cursor-color;
  border-right: 2px solid @syntax-cursor-color;
}
```

But feels a bit aggressive to be added to core. :smiling_imp:
