### ISSUE TITLE
cannot change selection color

### ISSUE THREAD

**Issue by schmurfy** [atom/atom#8213]
I want to change the selection color by using my user styles, I looked at how the "page" is built with the inspector and made various tests but none of them did anything, this is really frustrating...

What I tried:
```less
.selection .region { background-color: red }
```

I thought maybe order was the issue so I tried:
```less
.selection .region {
  border: 1px solid blue;
  background-color: blue !important;
}
```

When I look at the page source I see my styles added at the end in the header section, I see in its content what I added but if I inspect the ".selection .region" elements my style is not there.

I would be really glad if someone could guide me, I barely see the selection with my current theme and this is really annoying.

**Comment by kevinsawicki** [comment]
You need to target the [shadow DOM](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/) of the `atom-text-editor` element to style it.

This worked for me:

```css
atom-text-editor::shadow .selection .region {
  border: 1px solid blue;
  background-color: blue !important;
}
```

Closing this out, please let me know if this doesn't work for you.
