### ISSUE TITLE
Gutter line-number width minimum two characters

### ISSUE THREAD

**Issue by jacekkopecky** [atom/atom#8375]
This is a suggestion: the space for line numbers in the gutter should be at least two characters wide, so that the transition from 9 lines to 10 doesn't change the gutter width. 

The reasoning goes like this: this transition happens when we've just started writing a new file, it is quite likely (few files are below 9 lines), and can be a distracting unexpected movement in peripheral vision. 

I was torn out of concentration by this sudden movement once too many times, so now I have this in my `styles.less`:

``` less
atom-text-editor {
  &,
  &::shadow {
    .gutter .line-number {
      min-width: 4.5ch; // 4.5 and not 2 because there's something else there, too
    }
  }
}
```

But that feels sub-optimal.

Even better (but much harder to implement) would be a width that smoothly increases (it could be set to _log10(lines)+1_ ch, again minimum 2ch) so that gutter width never jumps during normal editing.
