### ISSUE TITLE
Cannot block comment code that starts with a comment

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#8512]
Selecting all the following code and then trying to comment it out does nothing.  This only affects languages that specify a comment with a start and end component (eg CSS, HTML).  I would expect it to comment out the following css code:

``` css
/* General Overrides */

.codelab code.prettyprint {
  color: white; /* default color in case offline */
}
```

ref https://github.com/atom/language-css/issues/39

**Comment by mnquintana** [comment]
I can reproduce this with CSS, but not with any grammar that uses single line comments denoted by a "start" but not an "end" (e.g. JS).

**Comment by eddiemonge** [comment]
What about JS using `/* */` syntax?

**Comment by 50Wliu** [comment]
JS does not repro this bug since it comments out code using `//`.  HTML however does.

**Comment by as-cii** [comment]
I have checked out this behavior on Sublime Text and the result is kinda correct, but still weird:

![sublime](https://cloud.githubusercontent.com/assets/482957/9524749/d8b64300-4ce0-11e5-8a7f-7adc80b0cbe7.gif)

As you can see, code is not actually being commented out. Although I agree that not responding to the user action is bizarre, would the behavior shown in the screenshot be acceptable for Atom?

/cc: @atom/feedback

**Comment by lee-dohm** [comment]
In any language that I know, block comments don't nest. So any selection that contains one or more block comments that is requested to be block commented cannot easily be honored. There are two solutions to *properly* block commenting the above example. Either:

```css
/**//* General Overrides *//*

.codelab code.prettyprint {
  color: white; *//* default color in case offline *//*
}*/
```

Or if we want to special case the "starting with a comment" situation:

```css
/* General Overrides */
/*
.codelab code.prettyprint {
  color: white; *//* default color in case offline *//*
}*/
```

There may be a number of other edge cases that I'm not seeing right now.
