### ISSUE TITLE
atom-panel does not respect editor font setups

### ISSUE THREAD

**Issue by chaserhkj** [atom/atom#8590]
`atom-panel` objects does not respect `*.editor.fontFamily` setups in `config.cson`, which together with issue #6214 is causing Chinese (and possibly other nonlatin characters) not displaying correctly in the application.

In #6214, setting up a Chinese font in  `*.editor.fontFamily` in `config.cson` solves Chinese displaying problems, but this issue causes fonts in panels not readable even though these options are setup as mentioned above.

Some screenshots:

![screen](https://cloud.githubusercontent.com/assets/1768423/9574431/6f7ec67a-4ff9-11e5-9e80-d16dc2499831.png)

The font in the mini-editor and the font in the list are apparently not the same.

![screen2](https://cloud.githubusercontent.com/assets/1768423/9574482/fe793df6-4ff9-11e5-8b50-61bd6ff4b928.png)

Chinese font not displaying correctly in tree-view panel.

![screen3](https://cloud.githubusercontent.com/assets/1768423/9573268/e0ac1e4a-4fec-11e5-8f4f-f6f1615a5430.png)

Chinese font not displaying correctly in clipboard panel from package aki77/atom-clipboard-plus, already reported as aki77/atom-clipboard-plus#6

My system:

```
Version 1.0.7
OS: Linux 64bit
Distro: Arch Linux
Package: atom-editor-bin
```

I don't know if this is a bug or an intended behavior, but I suggest that it though may not be a brilliant idea to make all `atom-panel`s using the same font setup from `*.editor.fontFamily`, cause the setup may be mainly mean to set the **editor** interface font, but adding another option that could change these fonts in other components of the interface is surely a good idea and should be welcomed.

atom/tree-view#501 may be related to this issue.

_For these who come up with the same problem as me_, here's a **workaround**:

Adding these lines to `styles.less`

``` less
atom-panel {
  font-family: "Liberation Mono", "WenQuanYi Micro Hei Mono" !important;
  // Replace with preferred fonts.
}
```

However, there may be some panels that use components like `<pre>` `<code>`, which has explicit font-family override rules in `bootstrap.css` or other stylesheets, and these rules will cause these components not accepting the generic rules we added above, so they should be specified alone:( Taking clipboard panel from aki77/atom-clipboard-plus, which uses `<pre>` for example )

``` less
atom-panel.clipboard-plus .select-list ol.list-group li pre{
  font-family: "Liberation Mono", "WenQuanYi Micro Hei Mono" !important;
}
```
