### ISSUE TITLE
Text rendering on OS X

### ISSUE THREAD

**Issue by williambout** [atom/atom#8844]
Text rendering on OS X could be improved, by using `text-rendering: optimizeLegibility;`
The issue is especially visible on a Retina display.
With `optimizeLegibility`, letter spacing is more homogeneous.

![Imgur](http://i.imgur.com/YbaKeLW.png)
`text-rendering: auto;`

![Imgur](http://i.imgur.com/v2JX6Gl.png)
`text-rendering: optimizeLegibility;`

**Comment by williambout** [comment]
However, `text-rendering: auto;` seems better on a @1x display ¯\_(ツ)_/¯

**Comment by mnquintana** [comment]
We could scope it with a media query if that's the case:

```css

@media (-webkit-min-device-pixel-ratio: 2) {
  .platform-darwin {
    text-rendering: optimizeLegibility;
  }
}
```
