### ISSUE TITLE
Can't style indent-guide if using Shadow DOM

### ISSUE THREAD

**Issue by frantic** [atom/atom#9400]
My `styles.less`:

```less
.indent-guide {
  color: red !important;
}
```

have no effect when Settings → Use Shadow DOM is on, but works fine when it's off. The description says this option is going away, I was wondering if there is a work around or maybe I'm doing it wrong?

**Comment by simurai** [comment]
@frantic To make it work with Shadow DOM enabled, `atom-text-editor::shadow` needs to be added to the selector. This should work:

```less
.indent-guide,
atom-text-editor::shadow .indent-guide {
  color: red !important;
}
```
