### ISSUE TITLE
Blurry fonts in Atom 1.2 on Linux Mint

### ISSUE THREAD

**Issue by skeyl** [atom/atom#9596]
After updating from 1.0 to 1.2 fonts are blurry. I'm on Mint 17.2.

I've tried setting this:

```less
atom-text-editor {
  -webkit-font-smoothing: none;
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}
```

And it is ignored completely.

Below is an example of what I'm seeing:

![selection_002](https://cloud.githubusercontent.com/assets/7646510/11166313/46e25342-8afc-11e5-8560-89f04317ab0f.png)

I tried some of the solutions in #9454 to no avail. Also tried the "solutions" I found via Google to no avail.

I disabled OS level hinting; nothing changed. I changed OS level hinting from none => full; nothing changed.
